using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CSharpCpu.Cpus.Z80
{
	class InstructionTable : IInstructionTable
	{
		static private InstructionInfo Create(string OpCode, string Mnemonic)
		{
			return null;
		}

		static InstructionInfo[] Instructions = new[]
		{
			Create("8E         ","ADC A,(HL)       "),
			Create("DD8E d     ","ADC A,(IX+d)     "),
			Create("FD8E d     ","ADC A,(IY+d)     "),
			Create("8F         ","ADC A,A          "),
			Create("88         ","ADC A,B          "),
			Create("89         ","ADC A,C          "),
			Create("8A         ","ADC A,D          "),
			Create("8B         ","ADC A,E          "),
			Create("8C         ","ADC A,H          "),
			Create("DD8C       ","ADC A,IXh        "),
			Create("DD8D       ","ADC A,IXl        "),
			Create("FD8C       ","ADC A,IYh        "),
			Create("FD8D       ","ADC A,IYl        "),
			Create("8D         ","ADC A,L          "),
			Create("CE n       ","ADC A,n          "),
			Create("ED4A       ","ADC HL,BC        "),
			Create("ED5A       ","ADC HL,DE        "),
			Create("ED6A       ","ADC HL,HL        "),
			Create("ED7A       ","ADC HL,SP        "),
			Create("86         ","ADD A,(HL)       "),
			Create("DD86 d     ","ADD A,(IX+d)     "),
			Create("FD86 d     ","ADD A,(IY+d)     "),
			Create("87         ","ADD A,A          "),
			Create("80         ","ADD A,B          "),
			Create("81         ","ADD A,C          "),
			Create("82         ","ADD A,D          "),
			Create("83         ","ADD A,E          "),
			Create("84         ","ADD A,H          "),
			Create("DD84       ","ADD A,IXh        "),
			Create("DD85       ","ADD A,IXl        "),
			Create("FD84       ","ADD A,IYh        "),
			Create("FD85       ","ADD A,IYl        "),
			Create("85         ","ADD A,L          "),
			Create("C6 n       ","ADD A,n          "),
			Create("09         ","ADD HL,BC        "),
			Create("19         ","ADD HL,DE        "),
			Create("29         ","ADD HL,HL        "),
			Create("39         ","ADD HL,SP        "),
			Create("DD09       ","ADD IX,BC        "),
			Create("DD19       ","ADD IX,DE        "),
			Create("DD29       ","ADD IX,IX        "),
			Create("DD39       ","ADD IX,SP        "),
			Create("FD09       ","ADD IY,BC        "),
			Create("FD19       ","ADD IY,DE        "),
			Create("FD29       ","ADD IY,IY        "),
			Create("FD39       ","ADD IY,SP        "),
			Create("A6         ","AND (HL)         "),
			Create("DDA6 d     ","AND (IX+d)       "),
			Create("FDA6 d     ","AND (IY+d)       "),
			Create("A7         ","AND A            "),
			Create("A0         ","AND B            "),
			Create("A1         ","AND C            "),
			Create("A2         ","AND D            "),
			Create("A3         ","AND E            "),
			Create("A4         ","AND H            "),
			Create("DDA4       ","AND IXh          "),
			Create("DDA5       ","AND IXl          "),
			Create("FDA4       ","AND IYh          "),
			Create("FDA5       ","AND IYl          "),
			Create("A5         ","AND L            "),
			Create("E6 n       ","AND n            "),
			Create("CB46       ","BIT 0,(HL)       "),
			Create("DDCB d 46  ","BIT 0,(IX+d)     "),
			Create("DDCB d 41  ","BIT 0,(IX+d)     "),
			Create("DDCB d 47  ","BIT 0,(IX+d)     "),
			Create("DDCB d 42  ","BIT 0,(IX+d)     "),
			Create("DDCB d 43  ","BIT 0,(IX+d)     "),
			Create("DDCB d 44  ","BIT 0,(IX+d)     "),
			Create("DDCB d 40  ","BIT 0,(IX+d)     "),
			Create("DDCB d 45  ","BIT 0,(IX+d)     "),
			Create("FDCB d 46  ","BIT 0,(IY+d)     "),
			Create("FDCB d 40  ","BIT 0,(IY+d)     "),
			Create("FDCB d 47  ","BIT 0,(IY+d)     "),
			Create("FDCB d 43  ","BIT 0,(IY+d)     "),
			Create("FDCB d 41  ","BIT 0,(IY+d)     "),
			Create("FDCB d 45  ","BIT 0,(IY+d)     "),
			Create("FDCB d 42  ","BIT 0,(IY+d)     "),
			Create("FDCB d 44  ","BIT 0,(IY+d)     "),
			Create("CB47       ","BIT 0,A          "),
			Create("CB40       ","BIT 0,B          "),
			Create("CB41       ","BIT 0,C          "),
			Create("CB42       ","BIT 0,D          "),
			Create("CB43       ","BIT 0,E          "),
			Create("CB44       ","BIT 0,H          "),
			Create("CB45       ","BIT 0,L          "),
			Create("CB4E       ","BIT 1,(HL)       "),
			Create("DDCB d 4E  ","BIT 1,(IX+d)     "),
			Create("DDCB d 4B  ","BIT 1,(IX+d)     "),
			Create("DDCB d 4F  ","BIT 1,(IX+d)     "),
			Create("DDCB d 4A  ","BIT 1,(IX+d)     "),
			Create("DDCB d 4C  ","BIT 1,(IX+d)     "),
			Create("DDCB d 49  ","BIT 1,(IX+d)     "),
			Create("DDCB d 48  ","BIT 1,(IX+d)     "),
			Create("DDCB d 4D  ","BIT 1,(IX+d)     "),
			Create("FDCB d 4E  ","BIT 1,(IY+d)     "),
			Create("FDCB d 48  ","BIT 1,(IY+d)     "),
			Create("FDCB d 4F  ","BIT 1,(IY+d)     "),
			Create("FDCB d 4D  ","BIT 1,(IY+d)     "),
			Create("FDCB d 4C  ","BIT 1,(IY+d)     "),
			Create("FDCB d 4B  ","BIT 1,(IY+d)     "),
			Create("FDCB d 4A  ","BIT 1,(IY+d)     "),
			Create("FDCB d 49  ","BIT 1,(IY+d)     "),
			Create("CB4F       ","BIT 1,A          "),
			Create("CB48       ","BIT 1,B          "),
			Create("CB49       ","BIT 1,C          "),
			Create("CB4A       ","BIT 1,D          "),
			Create("CB4B       ","BIT 1,E          "),
			Create("CB4C       ","BIT 1,H          "),
			Create("CB4D       ","BIT 1,L          "),
			Create("CB56       ","BIT 2,(HL)       "),
			Create("DDCB d 56  ","BIT 2,(IX+d)     "),
			Create("DDCB d 53  ","BIT 2,(IX+d)     "),
			Create("DDCB d 52  ","BIT 2,(IX+d)     "),
			Create("DDCB d 51  ","BIT 2,(IX+d)     "),
			Create("DDCB d 54  ","BIT 2,(IX+d)     "),
			Create("DDCB d 55  ","BIT 2,(IX+d)     "),
			Create("DDCB d 57  ","BIT 2,(IX+d)     "),
			Create("DDCB d 50  ","BIT 2,(IX+d)     "),
			Create("FDCB d 56  ","BIT 2,(IY+d)     "),
			Create("FDCB d 53  ","BIT 2,(IY+d)     "),
			Create("FDCB d 57  ","BIT 2,(IY+d)     "),
			Create("FDCB d 55  ","BIT 2,(IY+d)     "),
			Create("FDCB d 50  ","BIT 2,(IY+d)     "),
			Create("FDCB d 51  ","BIT 2,(IY+d)     "),
			Create("FDCB d 52  ","BIT 2,(IY+d)     "),
			Create("FDCB d 54  ","BIT 2,(IY+d)     "),
			Create("CB57       ","BIT 2,A          "),
			Create("CB50       ","BIT 2,B          "),
			Create("CB51       ","BIT 2,C          "),
			Create("CB52       ","BIT 2,D          "),
			Create("CB53       ","BIT 2,E          "),
			Create("CB54       ","BIT 2,H          "),
			Create("CB55       ","BIT 2,L          "),
			Create("CB5E       ","BIT 3,(HL)       "),
			Create("DDCB d 5E  ","BIT 3,(IX+d)     "),
			Create("DDCB d 58  ","BIT 3,(IX+d)     "),
			Create("DDCB d 5A  ","BIT 3,(IX+d)     "),
			Create("DDCB d 59  ","BIT 3,(IX+d)     "),
			Create("DDCB d 5B  ","BIT 3,(IX+d)     "),
			Create("DDCB d 5F  ","BIT 3,(IX+d)     "),
			Create("DDCB d 5D  ","BIT 3,(IX+d)     "),
			Create("DDCB d 5C  ","BIT 3,(IX+d)     "),
			Create("FDCB d 5E  ","BIT 3,(IY+d)     "),
			Create("FDCB d 5B  ","BIT 3,(IY+d)     "),
			Create("FDCB d 5A  ","BIT 3,(IY+d)     "),
			Create("FDCB d 5F  ","BIT 3,(IY+d)     "),
			Create("FDCB d 58  ","BIT 3,(IY+d)     "),
			Create("FDCB d 5C  ","BIT 3,(IY+d)     "),
			Create("FDCB d 59  ","BIT 3,(IY+d)     "),
			Create("FDCB d 5D  ","BIT 3,(IY+d)     "),
			Create("CB5F       ","BIT 3,A          "),
			Create("CB58       ","BIT 3,B          "),
			Create("CB59       ","BIT 3,C          "),
			Create("CB5A       ","BIT 3,D          "),
			Create("CB5B       ","BIT 3,E          "),
			Create("CB5C       ","BIT 3,H          "),
			Create("CB5D       ","BIT 3,L          "),
			Create("CB66       ","BIT 4,(HL)       "),
			Create("DDCB d 66  ","BIT 4,(IX+d)     "),
			Create("DDCB d 60  ","BIT 4,(IX+d)     "),
			Create("DDCB d 62  ","BIT 4,(IX+d)     "),
			Create("DDCB d 61  ","BIT 4,(IX+d)     "),
			Create("DDCB d 65  ","BIT 4,(IX+d)     "),
			Create("DDCB d 63  ","BIT 4,(IX+d)     "),
			Create("DDCB d 64  ","BIT 4,(IX+d)     "),
			Create("DDCB d 67  ","BIT 4,(IX+d)     "),
			Create("FDCB d 66  ","BIT 4,(IY+d)     "),
			Create("FDCB d 60  ","BIT 4,(IY+d)     "),
			Create("FDCB d 64  ","BIT 4,(IY+d)     "),
			Create("FDCB d 62  ","BIT 4,(IY+d)     "),
			Create("FDCB d 65  ","BIT 4,(IY+d)     "),
			Create("FDCB d 61  ","BIT 4,(IY+d)     "),
			Create("FDCB d 63  ","BIT 4,(IY+d)     "),
			Create("FDCB d 67  ","BIT 4,(IY+d)     "),
			Create("CB67       ","BIT 4,A          "),
			Create("CB60       ","BIT 4,B          "),
			Create("CB61       ","BIT 4,C          "),
			Create("CB62       ","BIT 4,D          "),
			Create("CB63       ","BIT 4,E          "),
			Create("CB64       ","BIT 4,H          "),
			Create("CB65       ","BIT 4,L          "),
			Create("CB6E       ","BIT 5,(HL)       "),
			Create("DDCB d 6E  ","BIT 5,(IX+d)     "),
			Create("DDCB d 69  ","BIT 5,(IX+d)     "),
			Create("DDCB d 6D  ","BIT 5,(IX+d)     "),
			Create("DDCB d 6F  ","BIT 5,(IX+d)     "),
			Create("DDCB d 68  ","BIT 5,(IX+d)     "),
			Create("DDCB d 6C  ","BIT 5,(IX+d)     "),
			Create("DDCB d 6B  ","BIT 5,(IX+d)     "),
			Create("DDCB d 6A  ","BIT 5,(IX+d)     "),
			Create("FDCB d 6E  ","BIT 5,(IY+d)     "),
			Create("FDCB d 69  ","BIT 5,(IY+d)     "),
			Create("FDCB d 68  ","BIT 5,(IY+d)     "),
			Create("FDCB d 6D  ","BIT 5,(IY+d)     "),
			Create("FDCB d 6A  ","BIT 5,(IY+d)     "),
			Create("FDCB d 6F  ","BIT 5,(IY+d)     "),
			Create("FDCB d 6B  ","BIT 5,(IY+d)     "),
			Create("FDCB d 6C  ","BIT 5,(IY+d)     "),
			Create("CB6F       ","BIT 5,A          "),
			Create("CB68       ","BIT 5,B          "),
			Create("CB69       ","BIT 5,C          "),
			Create("CB6A       ","BIT 5,D          "),
			Create("CB6B       ","BIT 5,E          "),
			Create("CB6C       ","BIT 5,H          "),
			Create("CB6D       ","BIT 5,L          "),
			Create("CB76       ","BIT 6,(HL)       "),
			Create("DDCB d 76  ","BIT 6,(IX+d)     "),
			Create("DDCB d 77  ","BIT 6,(IX+d)     "),
			Create("DDCB d 75  ","BIT 6,(IX+d)     "),
			Create("DDCB d 74  ","BIT 6,(IX+d)     "),
			Create("DDCB d 73  ","BIT 6,(IX+d)     "),
			Create("DDCB d 71  ","BIT 6,(IX+d)     "),
			Create("DDCB d 70  ","BIT 6,(IX+d)     "),
			Create("DDCB d 72  ","BIT 6,(IX+d)     "),
			Create("FDCB d 76  ","BIT 6,(IY+d)     "),
			Create("FDCB d 73  ","BIT 6,(IY+d)     "),
			Create("FDCB d 70  ","BIT 6,(IY+d)     "),
			Create("FDCB d 75  ","BIT 6,(IY+d)     "),
			Create("FDCB d 74  ","BIT 6,(IY+d)     "),
			Create("FDCB d 72  ","BIT 6,(IY+d)     "),
			Create("FDCB d 77  ","BIT 6,(IY+d)     "),
			Create("FDCB d 71  ","BIT 6,(IY+d)     "),
			Create("CB77       ","BIT 6,A          "),
			Create("CB70       ","BIT 6,B          "),
			Create("CB71       ","BIT 6,C          "),
			Create("CB72       ","BIT 6,D          "),
			Create("CB73       ","BIT 6,E          "),
			Create("CB74       ","BIT 6,H          "),
			Create("CB75       ","BIT 6,L          "),
			Create("CB7E       ","BIT 7,(HL)       "),
			Create("DDCB d 7E  ","BIT 7,(IX+d)     "),
			Create("DDCB d 7B  ","BIT 7,(IX+d)     "),
			Create("DDCB d 79  ","BIT 7,(IX+d)     "),
			Create("DDCB d 7F  ","BIT 7,(IX+d)     "),
			Create("DDCB d 7C  ","BIT 7,(IX+d)     "),
			Create("DDCB d 7A  ","BIT 7,(IX+d)     "),
			Create("DDCB d 7D  ","BIT 7,(IX+d)     "),
			Create("DDCB d 78  ","BIT 7,(IX+d)     "),
			Create("FDCB d 7E  ","BIT 7,(IY+d)     "),
			Create("FDCB d 78  ","BIT 7,(IY+d)     "),
			Create("FDCB d 7A  ","BIT 7,(IY+d)     "),
			Create("FDCB d 7F  ","BIT 7,(IY+d)     "),
			Create("FDCB d 7C  ","BIT 7,(IY+d)     "),
			Create("FDCB d 7B  ","BIT 7,(IY+d)     "),
			Create("FDCB d 79  ","BIT 7,(IY+d)     "),
			Create("FDCB d 7D  ","BIT 7,(IY+d)     "),
			Create("CB7F       ","BIT 7,A          "),
			Create("CB78       ","BIT 7,B          "),
			Create("CB79       ","BIT 7,C          "),
			Create("CB7A       ","BIT 7,D          "),
			Create("CB7B       ","BIT 7,E          "),
			Create("CB7C       ","BIT 7,H          "),
			Create("CB7D       ","BIT 7,L          "),
			Create("CD nn      ","CALL (nn)        "),
			Create("DC nn      ","CALL C,(nn)      "),
			Create("FC nn      ","CALL M,(nn)      "),
			Create("D4 nn      ","CALL NC,(nn)     "),
			Create("C4 nn      ","CALL NZ,(nn)     "),
			Create("F4 nn      ","CALL P,(nn)      "),
			Create("EC nn      ","CALL PE,(nn)     "),
			Create("E4 nn      ","CALL PO,(nn)     "),
			Create("CC nn      ","CALL Z,(nn)      "),
			Create("3F         ","CCF              "),
			Create("BE         ","CP (HL)          "),
			Create("DDBE d     ","CP (IX+d)        "),
			Create("FDBE d     ","CP (IY+d)        "),
			Create("BF         ","CP A             "),
			Create("B8         ","CP B             "),
			Create("B9         ","CP C             "),
			Create("BA         ","CP D             "),
			Create("BB         ","CP E             "),
			Create("BC         ","CP H             "),
			Create("DDBC       ","CP IXh           "),
			Create("DDBD       ","CP IXl           "),
			Create("FDBC       ","CP IYh           "),
			Create("FDBD       ","CP IYl           "),
			Create("BD         ","CP L             "),
			Create("FE n       ","CP n             "),
			Create("EDA9       ","CPD              "),
			Create("EDB9       ","CPDR             "),
			Create("EDA1       ","CPI              "),
			Create("EDB1       ","CPIR             "),
			Create("2F         ","CPL              "),
			Create("27         ","DAA              "),
			Create("35         ","DEC (HL)         "),
			Create("DD35 d     ","DEC (IX+d)       "),
			Create("FD35 d     ","DEC (IY+d)       "),
			Create("3D         ","DEC A            "),
			Create("05         ","DEC B            "),
			Create("0B         ","DEC BC           "),
			Create("0D         ","DEC C            "),
			Create("15         ","DEC D            "),
			Create("1B         ","DEC DE           "),
			Create("1D         ","DEC E            "),
			Create("25         ","DEC H            "),
			Create("2B         ","DEC HL           "),
			Create("DD2B       ","DEC IX           "),
			Create("DD25       ","DEC IXh          "),
			Create("DD2D       ","DEC IXl          "),
			Create("FD2B       ","DEC IY           "),
			Create("FD25       ","DEC IYh          "),
			Create("FD2D       ","DEC IYl          "),
			Create("2D         ","DEC L            "),
			Create("3B         ","DEC SP           "),
			Create("F3         ","DI               "),
			Create("10 e       ","DJNZ (PC+e)      "),
			Create("FB         ","EI               "),
			Create("E3         ","EX (SP),HL       "),
			Create("DDE3       ","EX (SP),IX       "),
			Create("FDE3       ","EX (SP),IY       "),
			Create("08         ","EX AF,AF'        "),
			Create("EB         ","EX DE,HL         "),
			Create("D9         ","EXX              "),
			Create("76         ","HALT             "),
			Create("ED46       ","IM 0             "),
			Create("ED6E       ","IM 0             "),
			Create("ED4E       ","IM 0             "),
			Create("ED66       ","IM 0             "),
			Create("ED56       ","IM 1             "),
			Create("ED76       ","IM 1             "),
			Create("ED5E       ","IM 2             "),
			Create("ED7E       ","IM 2             "),
			Create("ED78       ","IN A,(C)         "),
			Create("DB n       ","IN A,(n)         "),
			Create("ED40       ","IN B,(C)         "),
			Create("ED48       ","IN C,(C)         "),
			Create("ED50       ","IN D,(C)         "),
			Create("ED58       ","IN E,(C)         "),
			Create("ED70       ","IN F,(C)         "),
			Create("ED60       ","IN H,(C)         "),
			Create("ED68       ","IN L,(C)         "),
			Create("34         ","INC (HL)         "),
			Create("DD34 d     ","INC (IX+d)       "),
			Create("FD34 d     ","INC (IY+d)       "),
			Create("3C         ","INC A            "),
			Create("04         ","INC B            "),
			Create("03         ","INC BC           "),
			Create("0C         ","INC C            "),
			Create("14         ","INC D            "),
			Create("13         ","INC DE           "),
			Create("1C         ","INC E            "),
			Create("24         ","INC H            "),
			Create("23         ","INC HL           "),
			Create("DD23       ","INC IX           "),
			Create("DD24       ","INC IXh          "),
			Create("DD2C       ","INC IXl          "),
			Create("FD23       ","INC IY           "),
			Create("FD24       ","INC IYh          "),
			Create("FD2C       ","INC IYl          "),
			Create("2C         ","INC L            "),
			Create("33         ","INC SP           "),
			Create("EDAA       ","IND              "),
			Create("EDBA       ","INDR             "),
			Create("EDA2       ","INI              "),
			Create("EDB2       ","INIR             "),
			Create("E9         ","JP (HL)          "),
			Create("DDE9       ","JP (IX)          "),
			Create("FDE9       ","JP (IY)          "),
			Create("C3 nn      ","JP (nn)          "),
			Create("DA nn      ","JP C,(nn)        "),
			Create("FA nn      ","JP M,(nn)        "),
			Create("D2 nn      ","JP NC,(nn)       "),
			Create("C2 nn      ","JP NZ,(nn)       "),
			Create("F2 nn      ","JP P,(nn)        "),
			Create("EA nn      ","JP PE,(nn)       "),
			Create("E2 nn      ","JP PO,(nn)       "),
			Create("CA nn      ","JP Z,(nn)        "),
			Create("18 e       ","JR (PC+e)        "),
			Create("38 e       ","JR C,(PC+e)      "),
			Create("30 e       ","JR NC,(PC+e)     "),
			Create("20 e       ","JR NZ,(PC+e)     "),
			Create("28 e       ","JR Z,(PC+e)      "),
			Create("02         ","LD (BC),A        "),
			Create("12         ","LD (DE),A        "),
			Create("77         ","LD (HL),A        "),
			Create("70         ","LD (HL),B        "),
			Create("71         ","LD (HL),C        "),
			Create("72         ","LD (HL),D        "),
			Create("73         ","LD (HL),E        "),
			Create("74         ","LD (HL),H        "),
			Create("75         ","LD (HL),L        "),
			Create("36 n       ","LD (HL),n        "),
			Create("DD77 d     ","LD (IX+d),A      "),
			Create("DD70 d     ","LD (IX+d),B      "),
			Create("DD71 d     ","LD (IX+d),C      "),
			Create("DD72 d     ","LD (IX+d),D      "),
			Create("DD73 d     ","LD (IX+d),E      "),
			Create("DD74 d     ","LD (IX+d),H      "),
			Create("DD75 d     ","LD (IX+d),L      "),
			Create("DD36 d n   ","LD (IX+d),n      "),
			Create("FD77 d     ","LD (IY+d),A      "),
			Create("FD70 d     ","LD (IY+d),B      "),
			Create("FD71 d     ","LD (IY+d),C      "),
			Create("FD72 d     ","LD (IY+d),D      "),
			Create("FD73 d     ","LD (IY+d),E      "),
			Create("FD74 d     ","LD (IY+d),H      "),
			Create("FD75 d     ","LD (IY+d),L      "),
			Create("FD36 d n   ","LD (IY+d),n      "),
			Create("32 nn      ","LD (nn),A        "),
			Create("ED43 nn    ","LD (nn),BC       "),
			Create("ED53 nn    ","LD (nn),DE       "),
			Create("ED63 nn    ","LD (nn),HL       "),
			Create("22 nn      ","LD (nn),HL       "),
			Create("DD22 nn    ","LD (nn),IX       "),
			Create("FD22 nn    ","LD (nn),IY       "),
			Create("ED73 nn    ","LD (nn),SP       "),
			Create("0A         ","LD A,(BC)        "),
			Create("1A         ","LD A,(DE)        "),
			Create("7E         ","LD A,(HL)        "),
			Create("DD7E d     ","LD A,(IX+d)      "),
			Create("FD7E d     ","LD A,(IY+d)      "),
			Create("3A nn      ","LD A,(nn)        "),
			Create("7F         ","LD A,A           "),
			Create("78         ","LD A,B           "),
			Create("79         ","LD A,C           "),
			Create("7A         ","LD A,D           "),
			Create("7B         ","LD A,E           "),
			Create("7C         ","LD A,H           "),
			Create("ED57       ","LD A,I           "),
			Create("DD7C       ","LD A,IXh         "),
			Create("DD7D       ","LD A,IXl         "),
			Create("FD7C       ","LD A,IYh         "),
			Create("FD7D       ","LD A,IYl         "),
			Create("7D         ","LD A,L           "),
			Create("3E n       ","LD A,n           "),
			Create("ED5F       ","LD A,R           "),
			Create("DDCB d 87  ","LD A,RES 0,(IX+d)"),
			Create("FDCB d 87  ","LD A,RES 0,(IY+d)"),
			Create("DDCB d 8F  ","LD A,RES 1,(IX+d)"),
			Create("FDCB d 8F  ","LD A,RES 1,(IY+d)"),
			Create("DDCB d 97  ","LD A,RES 2,(IX+d)"),
			Create("FDCB d 97  ","LD A,RES 2,(IY+d)"),
			Create("DDCB d 9F  ","LD A,RES 3,(IX+d)"),
			Create("FDCB d 9F  ","LD A,RES 3,(IY+d)"),
			Create("DDCB d A7  ","LD A,RES 4,(IX+d)"),
			Create("FDCB d A7  ","LD A,RES 4,(IY+d)"),
			Create("DDCB d AF  ","LD A,RES 5,(IX+d)"),
			Create("FDCB d AF  ","LD A,RES 5,(IY+d)"),
			Create("DDCB d B7  ","LD A,RES 6,(IX+d)"),
			Create("FDCB d B7  ","LD A,RES 6,(IY+d)"),
			Create("DDCB d BF  ","LD A,RES 7,(IX+d)"),
			Create("FDCB d BF  ","LD A,RES 7,(IY+d)"),
			Create("DDCB d 17  ","LD A,RL (IX+d)   "),
			Create("FDCB d 17  ","LD A,RL (IY+d)   "),
			Create("DDCB d 07  ","LD A,RLC (IX+d)  "),
			Create("FDCB d 07  ","LD A,RLC (IY+d)  "),
			Create("DDCB d 1F  ","LD A,RR (IX+d)   "),
			Create("FDCB d 1F  ","LD A,RR (IY+d)   "),
			Create("DDCB d 0F  ","LD A,RRC (IX+d)  "),
			Create("FDCB d 0F  ","LD A,RRC (IY+d)  "),
			Create("DDCB d C7  ","LD A,SET 0,(IX+d)"),
			Create("FDCB d C7  ","LD A,SET 0,(IY+d)"),
			Create("DDCB d CF  ","LD A,SET 1,(IX+d)"),
			Create("FDCB d CF  ","LD A,SET 1,(IY+d)"),
			Create("DDCB d D7  ","LD A,SET 2,(IX+d)"),
			Create("FDCB d D7  ","LD A,SET 2,(IY+d)"),
			Create("DDCB d DF  ","LD A,SET 3,(IX+d)"),
			Create("FDCB d DF  ","LD A,SET 3,(IY+d)"),
			Create("DDCB d E7  ","LD A,SET 4,(IX+d)"),
			Create("FDCB d E7  ","LD A,SET 4,(IY+d)"),
			Create("DDCB d EF  ","LD A,SET 5,(IX+d)"),
			Create("FDCB d EF  ","LD A,SET 5,(IY+d)"),
			Create("DDCB d F7  ","LD A,SET 6,(IX+d)"),
			Create("FDCB d F7  ","LD A,SET 6,(IY+d)"),
			Create("DDCB d FF  ","LD A,SET 7,(IX+d)"),
			Create("FDCB d FF  ","LD A,SET 7,(IY+d)"),
			Create("DDCB d 27  ","LD A,SLA (IX+d)  "),
			Create("FDCB d 27  ","LD A,SLA (IY+d)  "),
			Create("DDCB d 37  ","LD A,SLL (IX+d)  "),
			Create("FDCB d 37  ","LD A,SLL (IY+d)  "),
			Create("DDCB d 2F  ","LD A,SRA (IX+d)  "),
			Create("FDCB d 2F  ","LD A,SRA (IY+d)  "),
			Create("DDCB d 3F  ","LD A,SRL (IX+d)  "),
			Create("FDCB d 3F  ","LD A,SRL (IY+d)  "),
			Create("46         ","LD B,(HL)        "),
			Create("DD46 d     ","LD B,(IX+d)      "),
			Create("FD46 d     ","LD B,(IY+d)      "),
			Create("47         ","LD B,A           "),
			Create("40         ","LD B,B           "),
			Create("41         ","LD B,C           "),
			Create("42         ","LD B,D           "),
			Create("43         ","LD B,E           "),
			Create("44         ","LD B,H           "),
			Create("DD44       ","LD B,IXh         "),
			Create("DD45       ","LD B,IXl         "),
			Create("FD44       ","LD B,IYh         "),
			Create("FD45       ","LD B,IYl         "),
			Create("45         ","LD B,L           "),
			Create("06 n       ","LD B,n           "),
			Create("DDCB d 80  ","LD B,RES 0,(IX+d)"),
			Create("FDCB d 80  ","LD B,RES 0,(IY+d)"),
			Create("DDCB d 88  ","LD B,RES 1,(IX+d)"),
			Create("FDCB d 88  ","LD B,RES 1,(IY+d)"),
			Create("DDCB d 90  ","LD B,RES 2,(IX+d)"),
			Create("FDCB d 90  ","LD B,RES 2,(IY+d)"),
			Create("DDCB d 98  ","LD B,RES 3,(IX+d)"),
			Create("FDCB d 98  ","LD B,RES 3,(IY+d)"),
			Create("DDCB d A0  ","LD B,RES 4,(IX+d)"),
			Create("FDCB d A0  ","LD B,RES 4,(IY+d)"),
			Create("DDCB d A8  ","LD B,RES 5,(IX+d)"),
			Create("FDCB d A8  ","LD B,RES 5,(IY+d)"),
			Create("DDCB d B0  ","LD B,RES 6,(IX+d)"),
			Create("FDCB d B0  ","LD B,RES 6,(IY+d)"),
			Create("DDCB d B8  ","LD B,RES 7,(IX+d)"),
			Create("FDCB d B8  ","LD B,RES 7,(IY+d)"),
			Create("DDCB d 10  ","LD B,RL (IX+d)   "),
			Create("FDCB d 10  ","LD B,RL (IY+d)   "),
			Create("DDCB d 00  ","LD B,RLC (IX+d)  "),
			Create("FDCB d 00  ","LD B,RLC (IY+d)  "),
			Create("DDCB d 18  ","LD B,RR (IX+d)   "),
			Create("FDCB d 18  ","LD B,RR (IY+d)   "),
			Create("DDCB d 08  ","LD B,RRC (IX+d)  "),
			Create("FDCB d 08  ","LD B,RRC (IY+d)  "),
			Create("DDCB d C0  ","LD B,SET 0,(IX+d)"),
			Create("FDCB d C0  ","LD B,SET 0,(IY+d)"),
			Create("DDCB d C8  ","LD B,SET 1,(IX+d)"),
			Create("FDCB d C8  ","LD B,SET 1,(IY+d)"),
			Create("DDCB d D0  ","LD B,SET 2,(IX+d)"),
			Create("FDCB d D0  ","LD B,SET 2,(IY+d)"),
			Create("DDCB d D8  ","LD B,SET 3,(IX+d)"),
			Create("FDCB d D8  ","LD B,SET 3,(IY+d)"),
			Create("DDCB d E0  ","LD B,SET 4,(IX+d)"),
			Create("FDCB d E0  ","LD B,SET 4,(IY+d)"),
			Create("DDCB d E8  ","LD B,SET 5,(IX+d)"),
			Create("FDCB d E8  ","LD B,SET 5,(IY+d)"),
			Create("DDCB d F0  ","LD B,SET 6,(IX+d)"),
			Create("FDCB d F0  ","LD B,SET 6,(IY+d)"),
			Create("DDCB d F8  ","LD B,SET 7,(IX+d)"),
			Create("FDCB d F8  ","LD B,SET 7,(IY+d)"),
			Create("DDCB d 20  ","LD B,SLA (IX+d)  "),
			Create("FDCB d 20  ","LD B,SLA (IY+d)  "),
			Create("DDCB d 30  ","LD B,SLL (IX+d)  "),
			Create("FDCB d 30  ","LD B,SLL (IY+d)  "),
			Create("DDCB d 28  ","LD B,SRA (IX+d)  "),
			Create("FDCB d 28  ","LD B,SRA (IY+d)  "),
			Create("DDCB d 38  ","LD B,SRL (IX+d)  "),
			Create("FDCB d 38  ","LD B,SRL (IY+d)  "),
			Create("ED4B nn    ","LD BC,(nn)       "),
			Create("01 nn      ","LD BC,nn         "),
			Create("4E         ","LD C,(HL)        "),
			Create("DD4E d     ","LD C,(IX+d)      "),
			Create("FD4E d     ","LD C,(IY+d)      "),
			Create("4F         ","LD C,A           "),
			Create("48         ","LD C,B           "),
			Create("49         ","LD C,C           "),
			Create("4A         ","LD C,D           "),
			Create("4B         ","LD C,E           "),
			Create("4C         ","LD C,H           "),
			Create("DD4C       ","LD C,IXh         "),
			Create("DD4D       ","LD C,IXl         "),
			Create("FD4C       ","LD C,IYh         "),
			Create("FD4D       ","LD C,IYl         "),
			Create("4D         ","LD C,L           "),
			Create("0E n       ","LD C,n           "),
			Create("DDCB d 81  ","LD C,RES 0,(IX+d)"),
			Create("FDCB d 81  ","LD C,RES 0,(IY+d)"),
			Create("DDCB d 89  ","LD C,RES 1,(IX+d)"),
			Create("FDCB d 89  ","LD C,RES 1,(IY+d)"),
			Create("DDCB d 91  ","LD C,RES 2,(IX+d)"),
			Create("FDCB d 91  ","LD C,RES 2,(IY+d)"),
			Create("DDCB d 99  ","LD C,RES 3,(IX+d)"),
			Create("FDCB d 99  ","LD C,RES 3,(IY+d)"),
			Create("DDCB d A1  ","LD C,RES 4,(IX+d)"),
			Create("FDCB d A1  ","LD C,RES 4,(IY+d)"),
			Create("DDCB d A9  ","LD C,RES 5,(IX+d)"),
			Create("FDCB d A9  ","LD C,RES 5,(IY+d)"),
			Create("DDCB d B1  ","LD C,RES 6,(IX+d)"),
			Create("FDCB d B1  ","LD C,RES 6,(IY+d)"),
			Create("DDCB d B9  ","LD C,RES 7,(IX+d)"),
			Create("FDCB d B9  ","LD C,RES 7,(IY+d)"),
			Create("DDCB d 11  ","LD C,RL (IX+d)   "),
			Create("FDCB d 11  ","LD C,RL (IY+d)   "),
			Create("DDCB d 01  ","LD C,RLC (IX+d)  "),
			Create("FDCB d 01  ","LD C,RLC (IY+d)  "),
			Create("DDCB d 19  ","LD C,RR (IX+d)   "),
			Create("FDCB d 19  ","LD C,RR (IY+d)   "),
			Create("DDCB d 09  ","LD C,RRC (IX+d)  "),
			Create("FDCB d 09  ","LD C,RRC (IY+d)  "),
			Create("DDCB d C1  ","LD C,SET 0,(IX+d)"),
			Create("FDCB d C1  ","LD C,SET 0,(IY+d)"),
			Create("DDCB d C9  ","LD C,SET 1,(IX+d)"),
			Create("FDCB d C9  ","LD C,SET 1,(IY+d)"),
			Create("DDCB d D1  ","LD C,SET 2,(IX+d)"),
			Create("FDCB d D1  ","LD C,SET 2,(IY+d)"),
			Create("DDCB d D9  ","LD C,SET 3,(IX+d)"),
			Create("FDCB d D9  ","LD C,SET 3,(IY+d)"),
			Create("DDCB d E1  ","LD C,SET 4,(IX+d)"),
			Create("FDCB d E1  ","LD C,SET 4,(IY+d)"),
			Create("DDCB d E9  ","LD C,SET 5,(IX+d)"),
			Create("FDCB d E9  ","LD C,SET 5,(IY+d)"),
			Create("DDCB d F1  ","LD C,SET 6,(IX+d)"),
			Create("FDCB d F1  ","LD C,SET 6,(IY+d)"),
			Create("DDCB d F9  ","LD C,SET 7,(IX+d)"),
			Create("FDCB d F9  ","LD C,SET 7,(IY+d)"),
			Create("DDCB d 21  ","LD C,SLA (IX+d)  "),
			Create("FDCB d 21  ","LD C,SLA (IY+d)  "),
			Create("DDCB d 31  ","LD C,SLL (IX+d)  "),
			Create("FDCB d 31  ","LD C,SLL (IY+d)  "),
			Create("DDCB d 29  ","LD C,SRA (IX+d)  "),
			Create("FDCB d 29  ","LD C,SRA (IY+d)  "),
			Create("DDCB d 39  ","LD C,SRL (IX+d)  "),
			Create("FDCB d 39  ","LD C,SRL (IY+d)  "),
			Create("56         ","LD D,(HL)        "),
			Create("DD56 d     ","LD D,(IX+d)      "),
			Create("FD56 d     ","LD D,(IY+d)      "),
			Create("57         ","LD D,A           "),
			Create("50         ","LD D,B           "),
			Create("51         ","LD D,C           "),
			Create("52         ","LD D,D           "),
			Create("53         ","LD D,E           "),
			Create("54         ","LD D,H           "),
			Create("DD54       ","LD D,IXh         "),
			Create("DD55       ","LD D,IXl         "),
			Create("FD54       ","LD D,IYh         "),
			Create("FD55       ","LD D,IYl         "),
			Create("55         ","LD D,L           "),
			Create("16 n       ","LD D,n           "),
			Create("DDCB d 82  ","LD D,RES 0,(IX+d)"),
			Create("FDCB d 82  ","LD D,RES 0,(IY+d)"),
			Create("DDCB d 8A  ","LD D,RES 1,(IX+d)"),
			Create("FDCB d 8A  ","LD D,RES 1,(IY+d)"),
			Create("DDCB d 92  ","LD D,RES 2,(IX+d)"),
			Create("FDCB d 92  ","LD D,RES 2,(IY+d)"),
			Create("DDCB d 9A  ","LD D,RES 3,(IX+d)"),
			Create("FDCB d 9A  ","LD D,RES 3,(IY+d)"),
			Create("DDCB d A2  ","LD D,RES 4,(IX+d)"),
			Create("FDCB d A2  ","LD D,RES 4,(IY+d)"),
			Create("DDCB d AA  ","LD D,RES 5,(IX+d)"),
			Create("FDCB d AA  ","LD D,RES 5,(IY+d)"),
			Create("DDCB d B2  ","LD D,RES 6,(IX+d)"),
			Create("FDCB d B2  ","LD D,RES 6,(IY+d)"),
			Create("DDCB d BA  ","LD D,RES 7,(IX+d)"),
			Create("FDCB d BA  ","LD D,RES 7,(IY+d)"),
			Create("DDCB d 12  ","LD D,RL (IX+d)   "),
			Create("FDCB d 12  ","LD D,RL (IY+d)   "),
			Create("DDCB d 02  ","LD D,RLC (IX+d)  "),
			Create("FDCB d 02  ","LD D,RLC (IY+d)  "),
			Create("DDCB d 1A  ","LD D,RR (IX+d)   "),
			Create("FDCB d 1A  ","LD D,RR (IY+d)   "),
			Create("DDCB d 0A  ","LD D,RRC (IX+d)  "),
			Create("FDCB d 0A  ","LD D,RRC (IY+d)  "),
			Create("DDCB d C2  ","LD D,SET 0,(IX+d)"),
			Create("FDCB d C2  ","LD D,SET 0,(IY+d)"),
			Create("DDCB d CA  ","LD D,SET 1,(IX+d)"),
			Create("FDCB d CA  ","LD D,SET 1,(IY+d)"),
			Create("DDCB d D2  ","LD D,SET 2,(IX+d)"),
			Create("FDCB d D2  ","LD D,SET 2,(IY+d)"),
			Create("DDCB d DA  ","LD D,SET 3,(IX+d)"),
			Create("FDCB d DA  ","LD D,SET 3,(IY+d)"),
			Create("DDCB d E2  ","LD D,SET 4,(IX+d)"),
			Create("FDCB d E2  ","LD D,SET 4,(IY+d)"),
			Create("DDCB d EA  ","LD D,SET 5,(IX+d)"),
			Create("FDCB d EA  ","LD D,SET 5,(IY+d)"),
			Create("DDCB d F2  ","LD D,SET 6,(IX+d)"),
			Create("FDCB d F2  ","LD D,SET 6,(IY+d)"),
			Create("DDCB d FA  ","LD D,SET 7,(IX+d)"),
			Create("FDCB d FA  ","LD D,SET 7,(IY+d)"),
			Create("DDCB d 22  ","LD D,SLA (IX+d)  "),
			Create("FDCB d 22  ","LD D,SLA (IY+d)  "),
			Create("DDCB d 32  ","LD D,SLL (IX+d)  "),
			Create("FDCB d 32  ","LD D,SLL (IY+d)  "),
			Create("DDCB d 2A  ","LD D,SRA (IX+d)  "),
			Create("FDCB d 2A  ","LD D,SRA (IY+d)  "),
			Create("DDCB d 3A  ","LD D,SRL (IX+d)  "),
			Create("FDCB d 3A  ","LD D,SRL (IY+d)  "),
			Create("ED5B nn    ","LD DE,(nn)       "),
			Create("11 nn      ","LD DE,nn         "),
			Create("5E         ","LD E,(HL)        "),
			Create("DD5E d     ","LD E,(IX+d)      "),
			Create("FD5E d     ","LD E,(IY+d)      "),
			Create("5F         ","LD E,A           "),
			Create("58         ","LD E,B           "),
			Create("59         ","LD E,C           "),
			Create("5A         ","LD E,D           "),
			Create("5B         ","LD E,E           "),
			Create("5C         ","LD E,H           "),
			Create("DD5C       ","LD E,IXh         "),
			Create("DD5D       ","LD E,IXl         "),
			Create("FD5C       ","LD E,IYh         "),
			Create("FD5D       ","LD E,IYl         "),
			Create("5D         ","LD E,L           "),
			Create("1E n       ","LD E,n           "),
			Create("DDCB d 83  ","LD E,RES 0,(IX+d)"),
			Create("FDCB d 83  ","LD E,RES 0,(IY+d)"),
			Create("DDCB d 8B  ","LD E,RES 1,(IX+d)"),
			Create("FDCB d 8B  ","LD E,RES 1,(IY+d)"),
			Create("DDCB d 93  ","LD E,RES 2,(IX+d)"),
			Create("FDCB d 93  ","LD E,RES 2,(IY+d)"),
			Create("DDCB d 9B  ","LD E,RES 3,(IX+d)"),
			Create("FDCB d 9B  ","LD E,RES 3,(IY+d)"),
			Create("DDCB d A3  ","LD E,RES 4,(IX+d)"),
			Create("FDCB d A3  ","LD E,RES 4,(IY+d)"),
			Create("DDCB d AB  ","LD E,RES 5,(IX+d)"),
			Create("FDCB d AB  ","LD E,RES 5,(IY+d)"),
			Create("DDCB d B3  ","LD E,RES 6,(IX+d)"),
			Create("FDCB d B3  ","LD E,RES 6,(IY+d)"),
			Create("DDCB d BB  ","LD E,RES 7,(IX+d)"),
			Create("FDCB d BB  ","LD E,RES 7,(IY+d)"),
			Create("DDCB d 13  ","LD E,RL (IX+d)   "),
			Create("FDCB d 13  ","LD E,RL (IY+d)   "),
			Create("DDCB d 03  ","LD E,RLC (IX+d)  "),
			Create("FDCB d 03  ","LD E,RLC (IY+d)  "),
			Create("DDCB d 1B  ","LD E,RR (IX+d)   "),
			Create("FDCB d 1B  ","LD E,RR (IY+d)   "),
			Create("DDCB d 0B  ","LD E,RRC (IX+d)  "),
			Create("FDCB d 0B  ","LD E,RRC (IY+d)  "),
			Create("DDCB d C3  ","LD E,SET 0,(IX+d)"),
			Create("FDCB d C3  ","LD E,SET 0,(IY+d)"),
			Create("DDCB d CB  ","LD E,SET 1,(IX+d)"),
			Create("FDCB d CB  ","LD E,SET 1,(IY+d)"),
			Create("DDCB d D3  ","LD E,SET 2,(IX+d)"),
			Create("FDCB d D3  ","LD E,SET 2,(IY+d)"),
			Create("DDCB d DB  ","LD E,SET 3,(IX+d)"),
			Create("FDCB d DB  ","LD E,SET 3,(IY+d)"),
			Create("DDCB d E3  ","LD E,SET 4,(IX+d)"),
			Create("FDCB d E3  ","LD E,SET 4,(IY+d)"),
			Create("DDCB d EB  ","LD E,SET 5,(IX+d)"),
			Create("FDCB d EB  ","LD E,SET 5,(IY+d)"),
			Create("DDCB d F3  ","LD E,SET 6,(IX+d)"),
			Create("FDCB d F3  ","LD E,SET 6,(IY+d)"),
			Create("DDCB d FB  ","LD E,SET 7,(IX+d)"),
			Create("FDCB d FB  ","LD E,SET 7,(IY+d)"),
			Create("DDCB d 23  ","LD E,SLA (IX+d)  "),
			Create("FDCB d 23  ","LD E,SLA (IY+d)  "),
			Create("DDCB d 33  ","LD E,SLL (IX+d)  "),
			Create("FDCB d 33  ","LD E,SLL (IY+d)  "),
			Create("DDCB d 2B  ","LD E,SRA (IX+d)  "),
			Create("FDCB d 2B  ","LD E,SRA (IY+d)  "),
			Create("DDCB d 3B  ","LD E,SRL (IX+d)  "),
			Create("FDCB d 3B  ","LD E,SRL (IY+d)  "),
			Create("66         ","LD H,(HL)        "),
			Create("DD66 d     ","LD H,(IX+d)      "),
			Create("FD66 d     ","LD H,(IY+d)      "),
			Create("67         ","LD H,A           "),
			Create("60         ","LD H,B           "),
			Create("61         ","LD H,C           "),
			Create("62         ","LD H,D           "),
			Create("63         ","LD H,E           "),
			Create("64         ","LD H,H           "),
			Create("65         ","LD H,L           "),
			Create("26 n       ","LD H,n           "),
			Create("DDCB d 84  ","LD H,RES 0,(IX+d)"),
			Create("FDCB d 84  ","LD H,RES 0,(IY+d)"),
			Create("DDCB d 8C  ","LD H,RES 1,(IX+d)"),
			Create("FDCB d 8C  ","LD H,RES 1,(IY+d)"),
			Create("DDCB d 94  ","LD H,RES 2,(IX+d)"),
			Create("FDCB d 94  ","LD H,RES 2,(IY+d)"),
			Create("DDCB d 9C  ","LD H,RES 3,(IX+d)"),
			Create("FDCB d 9C  ","LD H,RES 3,(IY+d)"),
			Create("DDCB d A4  ","LD H,RES 4,(IX+d)"),
			Create("FDCB d A4  ","LD H,RES 4,(IY+d)"),
			Create("DDCB d AC  ","LD H,RES 5,(IX+d)"),
			Create("FDCB d AC  ","LD H,RES 5,(IY+d)"),
			Create("DDCB d B4  ","LD H,RES 6,(IX+d)"),
			Create("FDCB d B4  ","LD H,RES 6,(IY+d)"),
			Create("DDCB d BC  ","LD H,RES 7,(IX+d)"),
			Create("FDCB d BC  ","LD H,RES 7,(IY+d)"),
			Create("DDCB d 14  ","LD H,RL (IX+d)   "),
			Create("FDCB d 14  ","LD H,RL (IY+d)   "),
			Create("DDCB d 04  ","LD H,RLC (IX+d)  "),
			Create("FDCB d 04  ","LD H,RLC (IY+d)  "),
			Create("DDCB d 1C  ","LD H,RR (IX+d)   "),
			Create("FDCB d 1C  ","LD H,RR (IY+d)   "),
			Create("DDCB d 0C  ","LD H,RRC (IX+d)  "),
			Create("FDCB d 0C  ","LD H,RRC (IY+d)  "),
			Create("DDCB d C4  ","LD H,SET 0,(IX+d)"),
			Create("FDCB d C4  ","LD H,SET 0,(IY+d)"),
			Create("DDCB d CC  ","LD H,SET 1,(IX+d)"),
			Create("FDCB d CC  ","LD H,SET 1,(IY+d)"),
			Create("DDCB d D4  ","LD H,SET 2,(IX+d)"),
			Create("FDCB d D4  ","LD H,SET 2,(IY+d)"),
			Create("DDCB d DC  ","LD H,SET 3,(IX+d)"),
			Create("FDCB d DC  ","LD H,SET 3,(IY+d)"),
			Create("DDCB d E4  ","LD H,SET 4,(IX+d)"),
			Create("FDCB d E4  ","LD H,SET 4,(IY+d)"),
			Create("DDCB d EC  ","LD H,SET 5,(IX+d)"),
			Create("FDCB d EC  ","LD H,SET 5,(IY+d)"),
			Create("DDCB d F4  ","LD H,SET 6,(IX+d)"),
			Create("FDCB d F4  ","LD H,SET 6,(IY+d)"),
			Create("DDCB d FC  ","LD H,SET 7,(IX+d)"),
			Create("FDCB d FC  ","LD H,SET 7,(IY+d)"),
			Create("DDCB d 24  ","LD H,SLA (IX+d)  "),
			Create("FDCB d 24  ","LD H,SLA (IY+d)  "),
			Create("DDCB d 34  ","LD H,SLL (IX+d)  "),
			Create("FDCB d 34  ","LD H,SLL (IY+d)  "),
			Create("DDCB d 2C  ","LD H,SRA (IX+d)  "),
			Create("FDCB d 2C  ","LD H,SRA (IY+d)  "),
			Create("DDCB d 3C  ","LD H,SRL (IX+d)  "),
			Create("FDCB d 3C  ","LD H,SRL (IY+d)  "),
			Create("ED6B nn    ","LD HL,(nn)       "),
			Create("2A nn      ","LD HL,(nn)       "),
			Create("21 nn      ","LD HL,nn         "),
			Create("ED47       ","LD I,A           "),
			Create("DD2A nn    ","LD IX,(nn)       "),
			Create("DD21 nn    ","LD IX,nn         "),
			Create("DD67       ","LD IXh,A         "),
			Create("DD60       ","LD IXh,B         "),
			Create("DD61       ","LD IXh,C         "),
			Create("DD62       ","LD IXh,D         "),
			Create("DD63       ","LD IXh,E         "),
			Create("DD64       ","LD IXh,IXh       "),
			Create("DD65       ","LD IXh,IXl       "),
			Create("DD26 n     ","LD IXh,n         "),
			Create("DD6F       ","LD IXl,A         "),
			Create("DD68       ","LD IXl,B         "),
			Create("DD69       ","LD IXl,C         "),
			Create("DD6A       ","LD IXl,D         "),
			Create("DD6B       ","LD IXl,E         "),
			Create("DD6C       ","LD IXl,IXh       "),
			Create("DD6D       ","LD IXl,IXl       "),
			Create("DD2E n     ","LD IXl,n         "),
			Create("FD2A nn    ","LD IY,(nn)       "),
			Create("FD21 nn    ","LD IY,nn         "),
			Create("FD67       ","LD IYh,A         "),
			Create("FD60       ","LD IYh,B         "),
			Create("FD61       ","LD IYh,C         "),
			Create("FD62       ","LD IYh,D         "),
			Create("FD63       ","LD IYh,E         "),
			Create("FD64       ","LD IYh,IYh       "),
			Create("FD65       ","LD IYh,IYl       "),
			Create("FD26 n     ","LD IYh,n         "),
			Create("FD6F       ","LD IYl,A         "),
			Create("FD68       ","LD IYl,B         "),
			Create("FD69       ","LD IYl,C         "),
			Create("FD6A       ","LD IYl,D         "),
			Create("FD6B       ","LD IYl,E         "),
			Create("FD6C       ","LD IYl,IYh       "),
			Create("FD6D       ","LD IYl,IYl       "),
			Create("FD2E n     ","LD IYl,n         "),
			Create("6E         ","LD L,(HL)        "),
			Create("DD6E d     ","LD L,(IX+d)      "),
			Create("FD6E d     ","LD L,(IY+d)      "),
			Create("6F         ","LD L,A           "),
			Create("68         ","LD L,B           "),
			Create("69         ","LD L,C           "),
			Create("6A         ","LD L,D           "),
			Create("6B         ","LD L,E           "),
			Create("6C         ","LD L,H           "),
			Create("6D         ","LD L,L           "),
			Create("2E n       ","LD L,n           "),
			Create("DDCB d 85  ","LD L,RES 0,(IX+d)"),
			Create("FDCB d 85  ","LD L,RES 0,(IY+d)"),
			Create("DDCB d 8D  ","LD L,RES 1,(IX+d)"),
			Create("FDCB d 8D  ","LD L,RES 1,(IY+d)"),
			Create("DDCB d 95  ","LD L,RES 2,(IX+d)"),
			Create("FDCB d 95  ","LD L,RES 2,(IY+d)"),
			Create("DDCB d 9D  ","LD L,RES 3,(IX+d)"),
			Create("FDCB d 9D  ","LD L,RES 3,(IY+d)"),
			Create("DDCB d A5  ","LD L,RES 4,(IX+d)"),
			Create("FDCB d A5  ","LD L,RES 4,(IY+d)"),
			Create("DDCB d AD  ","LD L,RES 5,(IX+d)"),
			Create("FDCB d AD  ","LD L,RES 5,(IY+d)"),
			Create("DDCB d B5  ","LD L,RES 6,(IX+d)"),
			Create("FDCB d B5  ","LD L,RES 6,(IY+d)"),
			Create("DDCB d BD  ","LD L,RES 7,(IX+d)"),
			Create("FDCB d BD  ","LD L,RES 7,(IY+d)"),
			Create("DDCB d 15  ","LD L,RL (IX+d)   "),
			Create("FDCB d 15  ","LD L,RL (IY+d)   "),
			Create("DDCB d 05  ","LD L,RLC (IX+d)  "),
			Create("FDCB d 05  ","LD L,RLC (IY+d)  "),
			Create("DDCB d 1D  ","LD L,RR (IX+d)   "),
			Create("FDCB d 1D  ","LD L,RR (IY+d)   "),
			Create("DDCB d 0D  ","LD L,RRC (IX+d)  "),
			Create("FDCB d 0D  ","LD L,RRC (IY+d)  "),
			Create("DDCB d C5  ","LD L,SET 0,(IX+d)"),
			Create("FDCB d C5  ","LD L,SET 0,(IY+d)"),
			Create("DDCB d CD  ","LD L,SET 1,(IX+d)"),
			Create("FDCB d CD  ","LD L,SET 1,(IY+d)"),
			Create("DDCB d D5  ","LD L,SET 2,(IX+d)"),
			Create("FDCB d D5  ","LD L,SET 2,(IY+d)"),
			Create("DDCB d DD  ","LD L,SET 3,(IX+d)"),
			Create("FDCB d DD  ","LD L,SET 3,(IY+d)"),
			Create("DDCB d E5  ","LD L,SET 4,(IX+d)"),
			Create("FDCB d E5  ","LD L,SET 4,(IY+d)"),
			Create("DDCB d ED  ","LD L,SET 5,(IX+d)"),
			Create("FDCB d ED  ","LD L,SET 5,(IY+d)"),
			Create("DDCB d F5  ","LD L,SET 6,(IX+d)"),
			Create("FDCB d F5  ","LD L,SET 6,(IY+d)"),
			Create("DDCB d FD  ","LD L,SET 7,(IX+d)"),
			Create("FDCB d FD  ","LD L,SET 7,(IY+d)"),
			Create("DDCB d 25  ","LD L,SLA (IX+d)  "),
			Create("FDCB d 25  ","LD L,SLA (IY+d)  "),
			Create("DDCB d 35  ","LD L,SLL (IX+d)  "),
			Create("FDCB d 35  ","LD L,SLL (IY+d)  "),
			Create("DDCB d 2D  ","LD L,SRA (IX+d)  "),
			Create("FDCB d 2D  ","LD L,SRA (IY+d)  "),
			Create("DDCB d 3D  ","LD L,SRL (IX+d)  "),
			Create("FDCB d 3D  ","LD L,SRL (IY+d)  "),
			Create("ED4F       ","LD R,A           "),
			Create("ED7B nn    ","LD SP,(nn)       "),
			Create("F9         ","LD SP,HL         "),
			Create("DDF9       ","LD SP,IX         "),
			Create("FDF9       ","LD SP,IY         "),
			Create("31 nn      ","LD SP,nn         "),
			Create("EDA8       ","LDD              "),
			Create("EDB8       ","LDDR             "),
			Create("EDA0       ","LDI              "),
			Create("EDB0       ","LDIR             "),
			Create("ED44       ","NEG              "),
			Create("ED64       ","NEG              "),
			Create("ED6C       ","NEG              "),
			Create("ED74       ","NEG              "),
			Create("ED5C       ","NEG              "),
			Create("ED7C       ","NEG              "),
			Create("ED54       ","NEG              "),
			Create("ED4C       ","NEG              "),
			Create("00         ","NOP              "),
			Create("B6         ","OR (HL)          "),
			Create("DDB6 d     ","OR (IX+d)        "),
			Create("FDB6 d     ","OR (IY+d)        "),
			Create("B7         ","OR A             "),
			Create("B0         ","OR B             "),
			Create("B1         ","OR C             "),
			Create("B2         ","OR D             "),
			Create("B3         ","OR E             "),
			Create("B4         ","OR H             "),
			Create("DDB4       ","OR IXh           "),
			Create("DDB5       ","OR IXl           "),
			Create("FDB4       ","OR IYh           "),
			Create("FDB5       ","OR IYl           "),
			Create("B5         ","OR L             "),
			Create("F6 n       ","OR n             "),
			Create("EDBB       ","OTDR             "),
			Create("EDB3       ","OTIR             "),
			Create("ED71       ","OUT (C),0        "),
			Create("ED79       ","OUT (C),A        "),
			Create("ED41       ","OUT (C),B        "),
			Create("ED49       ","OUT (C),C        "),
			Create("ED51       ","OUT (C),D        "),
			Create("ED59       ","OUT (C),E        "),
			Create("ED61       ","OUT (C),H        "),
			Create("ED69       ","OUT (C),L        "),
			Create("D3 n       ","OUT (n),A        "),
			Create("EDAB       ","OUTD             "),
			Create("EDA3       ","OUTI             "),
			Create("F1         ","POP AF           "),
			Create("C1         ","POP BC           "),
			Create("D1         ","POP DE           "),
			Create("E1         ","POP HL           "),
			Create("DDE1       ","POP IX           "),
			Create("FDE1       ","POP IY           "),
			Create("F5         ","PUSH AF          "),
			Create("C5         ","PUSH BC          "),
			Create("D5         ","PUSH DE          "),
			Create("E5         ","PUSH HL          "),
			Create("DDE5       ","PUSH IX          "),
			Create("FDE5       ","PUSH IY          "),
			Create("CB86       ","RES 0,(HL)       "),
			Create("DDCB d 86  ","RES 0,(IX+d)     "),
			Create("FDCB d 86  ","RES 0,(IY+d)     "),
			Create("CB87       ","RES 0,A          "),
			Create("CB80       ","RES 0,B          "),
			Create("CB81       ","RES 0,C          "),
			Create("CB82       ","RES 0,D          "),
			Create("CB83       ","RES 0,E          "),
			Create("CB84       ","RES 0,H          "),
			Create("CB85       ","RES 0,L          "),
			Create("CB8E       ","RES 1,(HL)       "),
			Create("DDCB d 8E  ","RES 1,(IX+d)     "),
			Create("FDCB d 8E  ","RES 1,(IY+d)     "),
			Create("CB8F       ","RES 1,A          "),
			Create("CB88       ","RES 1,B          "),
			Create("CB89       ","RES 1,C          "),
			Create("CB8A       ","RES 1,D          "),
			Create("CB8B       ","RES 1,E          "),
			Create("CB8C       ","RES 1,H          "),
			Create("CB8D       ","RES 1,L          "),
			Create("CB96       ","RES 2,(HL)       "),
			Create("DDCB d 96  ","RES 2,(IX+d)     "),
			Create("FDCB d 96  ","RES 2,(IY+d)     "),
			Create("CB97       ","RES 2,A          "),
			Create("CB90       ","RES 2,B          "),
			Create("CB91       ","RES 2,C          "),
			Create("CB92       ","RES 2,D          "),
			Create("CB93       ","RES 2,E          "),
			Create("CB94       ","RES 2,H          "),
			Create("CB95       ","RES 2,L          "),
			Create("CB9E       ","RES 3,(HL)       "),
			Create("DDCB d 9E  ","RES 3,(IX+d)     "),
			Create("FDCB d 9E  ","RES 3,(IY+d)     "),
			Create("CB9F       ","RES 3,A          "),
			Create("CB98       ","RES 3,B          "),
			Create("CB99       ","RES 3,C          "),
			Create("CB9A       ","RES 3,D          "),
			Create("CB9B       ","RES 3,E          "),
			Create("CB9C       ","RES 3,H          "),
			Create("CB9D       ","RES 3,L          "),
			Create("CBA6       ","RES 4,(HL)       "),
			Create("DDCB d A6  ","RES 4,(IX+d)     "),
			Create("FDCB d A6  ","RES 4,(IY+d)     "),
			Create("CBA7       ","RES 4,A          "),
			Create("CBA0       ","RES 4,B          "),
			Create("CBA1       ","RES 4,C          "),
			Create("CBA2       ","RES 4,D          "),
			Create("CBA3       ","RES 4,E          "),
			Create("CBA4       ","RES 4,H          "),
			Create("CBA5       ","RES 4,L          "),
			Create("CBAE       ","RES 5,(HL)       "),
			Create("DDCB d AE  ","RES 5,(IX+d)     "),
			Create("FDCB d AE  ","RES 5,(IY+d)     "),
			Create("CBAF       ","RES 5,A          "),
			Create("CBA8       ","RES 5,B          "),
			Create("CBA9       ","RES 5,C          "),
			Create("CBAA       ","RES 5,D          "),
			Create("CBAB       ","RES 5,E          "),
			Create("CBAC       ","RES 5,H          "),
			Create("CBAD       ","RES 5,L          "),
			Create("CBB6       ","RES 6,(HL)       "),
			Create("DDCB d B6  ","RES 6,(IX+d)     "),
			Create("FDCB d B6  ","RES 6,(IY+d)     "),
			Create("CBB7       ","RES 6,A          "),
			Create("CBB0       ","RES 6,B          "),
			Create("CBB1       ","RES 6,C          "),
			Create("CBB2       ","RES 6,D          "),
			Create("CBB3       ","RES 6,E          "),
			Create("CBB4       ","RES 6,H          "),
			Create("CBB5       ","RES 6,L          "),
			Create("CBBE       ","RES 7,(HL)       "),
			Create("DDCB d BE  ","RES 7,(IX+d)     "),
			Create("FDCB d BE  ","RES 7,(IY+d)     "),
			Create("CBBF       ","RES 7,A          "),
			Create("CBB8       ","RES 7,B          "),
			Create("CBB9       ","RES 7,C          "),
			Create("CBBA       ","RES 7,D          "),
			Create("CBBB       ","RES 7,E          "),
			Create("CBBC       ","RES 7,H          "),
			Create("CBBD       ","RES 7,L          "),
			Create("C9         ","RET              "),
			Create("D8         ","RET C            "),
			Create("F8         ","RET M            "),
			Create("D0         ","RET NC           "),
			Create("C0         ","RET NZ           "),
			Create("F0         ","RET P            "),
			Create("E8         ","RET PE           "),
			Create("E0         ","RET PO           "),
			Create("C8         ","RET Z            "),
			Create("ED4D       ","RETI             "),
			Create("ED45       ","RETN             "),
			Create("ED55       ","RETN             "),
			Create("ED65       ","RETN             "),
			Create("ED5D       ","RETN             "),
			Create("ED75       ","RETN             "),
			Create("ED6D       ","RETN             "),
			Create("ED7D       ","RETN             "),
			Create("CB16       ","RL (HL)          "),
			Create("DDCB d 16  ","RL (IX+d)        "),
			Create("FDCB d 16  ","RL (IY+d)        "),
			Create("CB17       ","RL A             "),
			Create("CB10       ","RL B             "),
			Create("CB11       ","RL C             "),
			Create("CB12       ","RL D             "),
			Create("CB13       ","RL E             "),
			Create("CB14       ","RL H             "),
			Create("CB15       ","RL L             "),
			Create("17         ","RLA              "),
			Create("CB06       ","RLC (HL)         "),
			Create("DDCB d 06  ","RLC (IX+d)       "),
			Create("FDCB d 06  ","RLC (IY+d)       "),
			Create("CB07       ","RLC A            "),
			Create("CB00       ","RLC B            "),
			Create("CB01       ","RLC C            "),
			Create("CB02       ","RLC D            "),
			Create("CB03       ","RLC E            "),
			Create("CB04       ","RLC H            "),
			Create("CB05       ","RLC L            "),
			Create("07         ","RLCA             "),
			Create("ED6F       ","RLD              "),
			Create("CB1E       ","RR (HL)          "),
			Create("DDCB d 1E  ","RR (IX+d)        "),
			Create("FDCB d 1E  ","RR (IY+d)        "),
			Create("CB1F       ","RR A             "),
			Create("CB18       ","RR B             "),
			Create("CB19       ","RR C             "),
			Create("CB1A       ","RR D             "),
			Create("CB1B       ","RR E             "),
			Create("CB1C       ","RR H             "),
			Create("CB1D       ","RR L             "),
			Create("1F         ","RRA              "),
			Create("CB0E       ","RRC (HL)         "),
			Create("DDCB d 0E  ","RRC (IX+d)       "),
			Create("FDCB d 0E  ","RRC (IY+d)       "),
			Create("CB0F       ","RRC A            "),
			Create("CB08       ","RRC B            "),
			Create("CB09       ","RRC C            "),
			Create("CB0A       ","RRC D            "),
			Create("CB0B       ","RRC E            "),
			Create("CB0C       ","RRC H            "),
			Create("CB0D       ","RRC L            "),
			Create("0F         ","RRCA             "),
			Create("ED67       ","RRD              "),
			Create("C7         ","RST 0H           "),
			Create("D7         ","RST 10H          "),
			Create("DF         ","RST 18H          "),
			Create("E7         ","RST 20H          "),
			Create("EF         ","RST 28H          "),
			Create("F7         ","RST 30H          "),
			Create("FF         ","RST 38H          "),
			Create("CF         ","RST 8H           "),
			Create("9E         ","SBC A,(HL)       "),
			Create("DD9E d     ","SBC A,(IX+d)     "),
			Create("FD9E d     ","SBC A,(IY+d)     "),
			Create("9F         ","SBC A,A          "),
			Create("98         ","SBC A,B          "),
			Create("99         ","SBC A,C          "),
			Create("9A         ","SBC A,D          "),
			Create("9B         ","SBC A,E          "),
			Create("9C         ","SBC A,H          "),
			Create("DD9C       ","SBC A,IXh        "),
			Create("DD9D       ","SBC A,IXl        "),
			Create("FD9C       ","SBC A,IYh        "),
			Create("FD9D       ","SBC A,IYl        "),
			Create("9D         ","SBC A,L          "),
			Create("DE n       ","SBC A,n          "),
			Create("ED42       ","SBC HL,BC        "),
			Create("ED52       ","SBC HL,DE        "),
			Create("ED62       ","SBC HL,HL        "),
			Create("ED72       ","SBC HL,SP        "),
			Create("37         ","SCF              "),
			Create("CBC6       ","SET 0,(HL)       "),
			Create("DDCB d C6  ","SET 0,(IX+d)     "),
			Create("FDCB d C6  ","SET 0,(IY+d)     "),
			Create("CBC7       ","SET 0,A          "),
			Create("CBC0       ","SET 0,B          "),
			Create("CBC1       ","SET 0,C          "),
			Create("CBC2       ","SET 0,D          "),
			Create("CBC3       ","SET 0,E          "),
			Create("CBC4       ","SET 0,H          "),
			Create("CBC5       ","SET 0,L          "),
			Create("CBCE       ","SET 1,(HL)       "),
			Create("DDCB d CE  ","SET 1,(IX+d)     "),
			Create("FDCB d CE  ","SET 1,(IY+d)     "),
			Create("CBCF       ","SET 1,A          "),
			Create("CBC8       ","SET 1,B          "),
			Create("CBC9       ","SET 1,C          "),
			Create("CBCA       ","SET 1,D          "),
			Create("CBCB       ","SET 1,E          "),
			Create("CBCC       ","SET 1,H          "),
			Create("CBCD       ","SET 1,L          "),
			Create("CBD6       ","SET 2,(HL)       "),
			Create("DDCB d D6  ","SET 2,(IX+d)     "),
			Create("FDCB d D6  ","SET 2,(IY+d)     "),
			Create("CBD7       ","SET 2,A          "),
			Create("CBD0       ","SET 2,B          "),
			Create("CBD1       ","SET 2,C          "),
			Create("CBD2       ","SET 2,D          "),
			Create("CBD3       ","SET 2,E          "),
			Create("CBD4       ","SET 2,H          "),
			Create("CBD5       ","SET 2,L          "),
			Create("CBDE       ","SET 3,(HL)       "),
			Create("DDCB d DE  ","SET 3,(IX+d)     "),
			Create("FDCB d DE  ","SET 3,(IY+d)     "),
			Create("CBDF       ","SET 3,A          "),
			Create("CBD8       ","SET 3,B          "),
			Create("CBD9       ","SET 3,C          "),
			Create("CBDA       ","SET 3,D          "),
			Create("CBDB       ","SET 3,E          "),
			Create("CBDC       ","SET 3,H          "),
			Create("CBDD       ","SET 3,L          "),
			Create("CBE6       ","SET 4,(HL)       "),
			Create("DDCB d E6  ","SET 4,(IX+d)     "),
			Create("FDCB d E6  ","SET 4,(IY+d)     "),
			Create("CBE7       ","SET 4,A          "),
			Create("CBE0       ","SET 4,B          "),
			Create("CBE1       ","SET 4,C          "),
			Create("CBE2       ","SET 4,D          "),
			Create("CBE3       ","SET 4,E          "),
			Create("CBE4       ","SET 4,H          "),
			Create("CBE5       ","SET 4,L          "),
			Create("CBEE       ","SET 5,(HL)       "),
			Create("DDCB d EE  ","SET 5,(IX+d)     "),
			Create("FDCB d EE  ","SET 5,(IY+d)     "),
			Create("CBEF       ","SET 5,A          "),
			Create("CBE8       ","SET 5,B          "),
			Create("CBE9       ","SET 5,C          "),
			Create("CBEA       ","SET 5,D          "),
			Create("CBEB       ","SET 5,E          "),
			Create("CBEC       ","SET 5,H          "),
			Create("CBED       ","SET 5,L          "),
			Create("CBF6       ","SET 6,(HL)       "),
			Create("DDCB d F6  ","SET 6,(IX+d)     "),
			Create("FDCB d F6  ","SET 6,(IY+d)     "),
			Create("CBF7       ","SET 6,A          "),
			Create("CBF0       ","SET 6,B          "),
			Create("CBF1       ","SET 6,C          "),
			Create("CBF2       ","SET 6,D          "),
			Create("CBF3       ","SET 6,E          "),
			Create("CBF4       ","SET 6,H          "),
			Create("CBF5       ","SET 6,L          "),
			Create("CBFE       ","SET 7,(HL)       "),
			Create("DDCB d FE  ","SET 7,(IX+d)     "),
			Create("FDCB d FE  ","SET 7,(IY+d)     "),
			Create("CBFF       ","SET 7,A          "),
			Create("CBF8       ","SET 7,B          "),
			Create("CBF9       ","SET 7,C          "),
			Create("CBFA       ","SET 7,D          "),
			Create("CBFB       ","SET 7,E          "),
			Create("CBFC       ","SET 7,H          "),
			Create("CBFD       ","SET 7,L          "),
			Create("CB26       ","SLA (HL)         "),
			Create("DDCB d 26  ","SLA (IX+d)       "),
			Create("FDCB d 26  ","SLA (IY+d)       "),
			Create("CB27       ","SLA A            "),
			Create("CB20       ","SLA B            "),
			Create("CB21       ","SLA C            "),
			Create("CB22       ","SLA D            "),
			Create("CB23       ","SLA E            "),
			Create("CB24       ","SLA H            "),
			Create("CB25       ","SLA L            "),
			Create("CB36       ","SLL (HL)         "),
			Create("DDCB d 36  ","SLL (IX+d)       "),
			Create("FDCB d 36  ","SLL (IY+d)       "),
			Create("CB37       ","SLL A            "),
			Create("CB30       ","SLL B            "),
			Create("CB31       ","SLL C            "),
			Create("CB32       ","SLL D            "),
			Create("CB33       ","SLL E            "),
			Create("CB34       ","SLL H            "),
			Create("CB35       ","SLL L            "),
			Create("CB2E       ","SRA (HL)         "),
			Create("DDCB d 2E  ","SRA (IX+d)       "),
			Create("FDCB d 2E  ","SRA (IY+d)       "),
			Create("CB2F       ","SRA A            "),
			Create("CB28       ","SRA B            "),
			Create("CB29       ","SRA C            "),
			Create("CB2A       ","SRA D            "),
			Create("CB2B       ","SRA E            "),
			Create("CB2C       ","SRA H            "),
			Create("CB2D       ","SRA L            "),
			Create("CB3E       ","SRL (HL)         "),
			Create("DDCB d 3E  ","SRL (IX+d)       "),
			Create("FDCB d 3E  ","SRL (IY+d)       "),
			Create("CB3F       ","SRL A            "),
			Create("CB38       ","SRL B            "),
			Create("CB39       ","SRL C            "),
			Create("CB3A       ","SRL D            "),
			Create("CB3B       ","SRL E            "),
			Create("CB3C       ","SRL H            "),
			Create("CB3D       ","SRL L            "),
			Create("96         ","SUB A,(HL)       "),
			Create("DD96 d     ","SUB A,(IX+d)     "),
			Create("FD96 d     ","SUB A,(IY+d)     "),
			Create("97         ","SUB A,A          "),
			Create("90         ","SUB A,B          "),
			Create("91         ","SUB A,C          "),
			Create("92         ","SUB A,D          "),
			Create("93         ","SUB A,E          "),
			Create("94         ","SUB A,H          "),
			Create("DD94       ","SUB A,IXh        "),
			Create("DD95       ","SUB A,IXl        "),
			Create("FD94       ","SUB A,IYh        "),
			Create("FD95       ","SUB A,IYl        "),
			Create("95         ","SUB A,L          "),
			Create("D6 n       ","SUB A,n          "),
			Create("AE         ","XOR (HL)         "),
			Create("DDAE d     ","XOR (IX+d)       "),
			Create("FDAE d     ","XOR (IY+d)       "),
			Create("AF         ","XOR A            "),
			Create("A8         ","XOR B            "),
			Create("A9         ","XOR C            "),
			Create("AA         ","XOR D            "),
			Create("AB         ","XOR E            "),
			Create("AC         ","XOR H            "),
			Create("DDAC       ","XOR IXh          "),
			Create("DDAD       ","XOR IXl          "),
			Create("FDAC       ","XOR IYh          "),
			Create("FDAD       ","XOR IYl          "),
			Create("AD         ","XOR L            "),
			Create("EE n       ","XOR n            "),
		};

		public InstructionFlags InstructionFlags
		{
			get { throw new NotImplementedException(); }
		}
	}
}
