using CSharpCpu.Decoder;
using SafeILGenerator.Ast;
using SafeILGenerator.Ast.Nodes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace CSharpCpu.Cpus.Z80
{
	/// <summary>
	/// 
	/// </summary>
	/// <see cref="http://pastraiser.com/cpu/gameboy/gameboy_opcodes.html"/>
	/// <see cref="http://wikiti.brandonw.net/?title=Z80_Instruction_Set"/>
	/// <see cref="http://www.z80.info/z80inst.txt"/>
	public sealed partial class InstructionTable : IInstructionTable
	{
		public static InstructionInfo[] Instructions { get { return _Instructions.Value; } }

		public enum Version
		{
			Z80 = 0,
			Gameboy = 1,
		}

		private static InstructionInfo[] CreateInstructionList(Version Version)
		{
			// Read InstructionData 4
			// Read Data 3 (%n)
			var Instructions = new List<InstructionInfo>();
			Instructions.Add(Instruction("8F         ", "ADC A,A           ", 4));
			Instructions.Add(Instruction("88         ", "ADC A,B           ", 4));
			Instructions.Add(Instruction("89         ", "ADC A,C           ", 4));
			Instructions.Add(Instruction("8A         ", "ADC A,D           ", 4));
			Instructions.Add(Instruction("8B         ", "ADC A,E           ", 4));
			Instructions.Add(Instruction("8C         ", "ADC A,H           ", 4));
			Instructions.Add(Instruction("8D         ", "ADC A,L           ", 4));
			Instructions.Add(Instruction("DD8C       ", "ADC A,IXh         ", 4));
			Instructions.Add(Instruction("DD8D       ", "ADC A,IXl         ", 4));
			Instructions.Add(Instruction("FD8C       ", "ADC A,IYh         ", 4));
			Instructions.Add(Instruction("FD8D       ", "ADC A,IYl         ", 4));
			Instructions.Add(Instruction("CE %n      ", "ADC A,%n          ", 7));
			Instructions.Add(Instruction("8E         ", "ADC A,(HL)        ", 7));
			Instructions.Add(Instruction("DD8E %d    ", "ADC A,(IX+%d)     ", 19));
			Instructions.Add(Instruction("FD8E %d    ", "ADC A,(IY+%d)     ", 19));

			Instructions.Add(Instruction("ED4A       ", "ADC HL,BC         ", 15));
			Instructions.Add(Instruction("ED5A       ", "ADC HL,DE         ", 15));
			Instructions.Add(Instruction("ED6A       ", "ADC HL,HL         ", 15));
			Instructions.Add(Instruction("ED7A       ", "ADC HL,SP         ", 15));

			Instructions.Add(Instruction("87         ", "ADD A,A           ", 4));
			Instructions.Add(Instruction("80         ", "ADD A,B           ", 4));
			Instructions.Add(Instruction("81         ", "ADD A,C           ", 4));
			Instructions.Add(Instruction("82         ", "ADD A,D           ", 4));
			Instructions.Add(Instruction("83         ", "ADD A,E           ", 4));
			Instructions.Add(Instruction("84         ", "ADD A,H           ", 4));
			Instructions.Add(Instruction("85         ", "ADD A,L           ", 4));
			Instructions.Add(Instruction("DD84       ", "ADD A,IXh         ", 4));
			Instructions.Add(Instruction("DD85       ", "ADD A,IXl         ", 4));
			Instructions.Add(Instruction("FD84       ", "ADD A,IYh         ", 4));
			Instructions.Add(Instruction("FD85       ", "ADD A,IYl         ", 4));
			Instructions.Add(Instruction("C6 %n      ", "ADD A,%n          ", 7));
			Instructions.Add(Instruction("86         ", "ADD A,(HL)        ", 7));
			Instructions.Add(Instruction("DD86 %d    ", "ADD A,(IX+%d)     ", 19));
			Instructions.Add(Instruction("FD86 %d    ", "ADD A,(IY+%d)     ", 19));

			Instructions.Add(Instruction("09         ", "ADD HL,BC         ", 11));
			Instructions.Add(Instruction("19         ", "ADD HL,DE         ", 11));
			Instructions.Add(Instruction("29         ", "ADD HL,HL         ", 11));
			Instructions.Add(Instruction("39         ", "ADD HL,SP         ", 11));

			Instructions.Add(Instruction("DD09       ", "ADD IX,BC         ", 15));
			Instructions.Add(Instruction("DD19       ", "ADD IX,DE         ", 15));
			Instructions.Add(Instruction("DD29       ", "ADD IX,IX         ", 15));
			Instructions.Add(Instruction("DD39       ", "ADD IX,SP         ", 15));
			
			Instructions.Add(Instruction("FD09       ", "ADD IY,BC         ", 15));
			Instructions.Add(Instruction("FD19       ", "ADD IY,DE         ", 15));
			Instructions.Add(Instruction("FD29       ", "ADD IY,IY         ", 15));
			Instructions.Add(Instruction("FD39       ", "ADD IY,SP         ", 15));

			Instructions.Add(Instruction("A7         ", "AND A             ", 4));
			Instructions.Add(Instruction("A0         ", "AND B             ", 4));
			Instructions.Add(Instruction("A1         ", "AND C             ", 4));
			Instructions.Add(Instruction("A2         ", "AND D             ", 4));
			Instructions.Add(Instruction("A3         ", "AND E             ", 4));
			Instructions.Add(Instruction("A4         ", "AND H             ", 4));
			Instructions.Add(Instruction("A5         ", "AND L             ", 4));
			Instructions.Add(Instruction("DDA4       ", "AND IXh           ", 4));
			Instructions.Add(Instruction("DDA5       ", "AND IXl           ", 4));
			Instructions.Add(Instruction("FDA4       ", "AND IYh           ", 4));
			Instructions.Add(Instruction("FDA5       ", "AND IYl           ", 4));
			Instructions.Add(Instruction("E6 %n      ", "AND %n            ", 7));
			Instructions.Add(Instruction("A6         ", "AND (HL)          ", 7));
			Instructions.Add(Instruction("DDA6 %d    ", "AND (IX+%d)       ", 19));
			Instructions.Add(Instruction("FDA6 %d    ", "AND (IY+%d)       ", 19));

			Instructions.Add(Instruction("CB46       ", "BIT 0,(HL)        ", 12));
			Instructions.Add(Instruction("DDCB %d 46 ", "BIT 0,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 41 ", "BIT 0,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 47 ", "BIT 0,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 42 ", "BIT 0,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 43 ", "BIT 0,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 44 ", "BIT 0,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 40 ", "BIT 0,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 45 ", "BIT 0,(IX+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 46 ", "BIT 0,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 40 ", "BIT 0,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 47 ", "BIT 0,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 43 ", "BIT 0,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 41 ", "BIT 0,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 45 ", "BIT 0,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 42 ", "BIT 0,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 44 ", "BIT 0,(IY+%d)     ", 20));
			Instructions.Add(Instruction("CB47       ", "BIT 0,A           ", 8));
			Instructions.Add(Instruction("CB40       ", "BIT 0,B           ", 8));
			Instructions.Add(Instruction("CB41       ", "BIT 0,C           ", 8));
			Instructions.Add(Instruction("CB42       ", "BIT 0,D           ", 8));
			Instructions.Add(Instruction("CB43       ", "BIT 0,E           ", 8));
			Instructions.Add(Instruction("CB44       ", "BIT 0,H           ", 8));
			Instructions.Add(Instruction("CB45       ", "BIT 0,L           ", 8));

			Instructions.Add(Instruction("CB4E       ", "BIT 1,(HL)        ", 12));
			Instructions.Add(Instruction("DDCB %d 4E ", "BIT 1,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 4B ", "BIT 1,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 4F ", "BIT 1,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 4A ", "BIT 1,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 4C ", "BIT 1,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 49 ", "BIT 1,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 48 ", "BIT 1,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 4D ", "BIT 1,(IX+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 4E ", "BIT 1,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 48 ", "BIT 1,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 4F ", "BIT 1,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 4D ", "BIT 1,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 4C ", "BIT 1,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 4B ", "BIT 1,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 4A ", "BIT 1,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 49 ", "BIT 1,(IY+%d)     ", 20));
			Instructions.Add(Instruction("CB4F       ", "BIT 1,A           ", 8));
			Instructions.Add(Instruction("CB48       ", "BIT 1,B           ", 8));
			Instructions.Add(Instruction("CB49       ", "BIT 1,C           ", 8));
			Instructions.Add(Instruction("CB4A       ", "BIT 1,D           ", 8));
			Instructions.Add(Instruction("CB4B       ", "BIT 1,E           ", 8));
			Instructions.Add(Instruction("CB4C       ", "BIT 1,H           ", 8));
			Instructions.Add(Instruction("CB4D       ", "BIT 1,L           ", 8));

			Instructions.Add(Instruction("CB56       ", "BIT 2,(HL)        ", 12));
			Instructions.Add(Instruction("DDCB %d 56 ", "BIT 2,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 53 ", "BIT 2,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 52 ", "BIT 2,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 51 ", "BIT 2,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 54 ", "BIT 2,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 55 ", "BIT 2,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 57 ", "BIT 2,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 50 ", "BIT 2,(IX+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 56 ", "BIT 2,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 53 ", "BIT 2,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 57 ", "BIT 2,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 55 ", "BIT 2,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 50 ", "BIT 2,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 51 ", "BIT 2,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 52 ", "BIT 2,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 54 ", "BIT 2,(IY+%d)     ", 20));
			Instructions.Add(Instruction("CB57       ", "BIT 2,A           ", 8));
			Instructions.Add(Instruction("CB50       ", "BIT 2,B           ", 8));
			Instructions.Add(Instruction("CB51       ", "BIT 2,C           ", 8));
			Instructions.Add(Instruction("CB52       ", "BIT 2,D           ", 8));
			Instructions.Add(Instruction("CB53       ", "BIT 2,E           ", 8));
			Instructions.Add(Instruction("CB54       ", "BIT 2,H           ", 8));
			Instructions.Add(Instruction("CB55       ", "BIT 2,L           ", 8));

			Instructions.Add(Instruction("CB5E       ", "BIT 3,(HL)        ", 12));
			Instructions.Add(Instruction("DDCB %d 5E ", "BIT 3,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 58 ", "BIT 3,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 5A ", "BIT 3,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 59 ", "BIT 3,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 5B ", "BIT 3,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 5F ", "BIT 3,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 5D ", "BIT 3,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 5C ", "BIT 3,(IX+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 5E ", "BIT 3,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 5B ", "BIT 3,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 5A ", "BIT 3,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 5F ", "BIT 3,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 58 ", "BIT 3,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 5C ", "BIT 3,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 59 ", "BIT 3,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 5D ", "BIT 3,(IY+%d)     ", 20));
			Instructions.Add(Instruction("CB5F       ", "BIT 3,A           ", 8));
			Instructions.Add(Instruction("CB58       ", "BIT 3,B           ", 8));
			Instructions.Add(Instruction("CB59       ", "BIT 3,C           ", 8));
			Instructions.Add(Instruction("CB5A       ", "BIT 3,D           ", 8));
			Instructions.Add(Instruction("CB5B       ", "BIT 3,E           ", 8));
			Instructions.Add(Instruction("CB5C       ", "BIT 3,H           ", 8));
			Instructions.Add(Instruction("CB5D       ", "BIT 3,L           ", 8));

			Instructions.Add(Instruction("CB66       ", "BIT 4,(HL)        ", 12));
			Instructions.Add(Instruction("DDCB %d 66 ", "BIT 4,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 60 ", "BIT 4,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 62 ", "BIT 4,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 61 ", "BIT 4,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 65 ", "BIT 4,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 63 ", "BIT 4,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 64 ", "BIT 4,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 67 ", "BIT 4,(IX+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 66 ", "BIT 4,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 60 ", "BIT 4,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 64 ", "BIT 4,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 62 ", "BIT 4,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 65 ", "BIT 4,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 61 ", "BIT 4,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 63 ", "BIT 4,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 67 ", "BIT 4,(IY+%d)     ", 20));
			Instructions.Add(Instruction("CB67       ", "BIT 4,A           ", 8));
			Instructions.Add(Instruction("CB60       ", "BIT 4,B           ", 8));
			Instructions.Add(Instruction("CB61       ", "BIT 4,C           ", 8));
			Instructions.Add(Instruction("CB62       ", "BIT 4,D           ", 8));
			Instructions.Add(Instruction("CB63       ", "BIT 4,E           ", 8));
			Instructions.Add(Instruction("CB64       ", "BIT 4,H           ", 8));
			Instructions.Add(Instruction("CB65       ", "BIT 4,L           ", 8));

			Instructions.Add(Instruction("CB6E       ", "BIT 5,(HL)        ", 12));
			Instructions.Add(Instruction("DDCB %d 6E ", "BIT 5,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 69 ", "BIT 5,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 6D ", "BIT 5,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 6F ", "BIT 5,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 68 ", "BIT 5,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 6C ", "BIT 5,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 6B ", "BIT 5,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 6A ", "BIT 5,(IX+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 6E ", "BIT 5,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 69 ", "BIT 5,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 68 ", "BIT 5,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 6D ", "BIT 5,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 6A ", "BIT 5,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 6F ", "BIT 5,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 6B ", "BIT 5,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 6C ", "BIT 5,(IY+%d)     ", 20));
			Instructions.Add(Instruction("CB6F       ", "BIT 5,A           ", 8));
			Instructions.Add(Instruction("CB68       ", "BIT 5,B           ", 8));
			Instructions.Add(Instruction("CB69       ", "BIT 5,C           ", 8));
			Instructions.Add(Instruction("CB6A       ", "BIT 5,D           ", 8));
			Instructions.Add(Instruction("CB6B       ", "BIT 5,E           ", 8));
			Instructions.Add(Instruction("CB6C       ", "BIT 5,H           ", 8));
			Instructions.Add(Instruction("CB6D       ", "BIT 5,L           ", 8));

			Instructions.Add(Instruction("CB76       ", "BIT 6,(HL)        ", 12));
			Instructions.Add(Instruction("DDCB %d 76 ", "BIT 6,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 77 ", "BIT 6,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 75 ", "BIT 6,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 74 ", "BIT 6,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 73 ", "BIT 6,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 71 ", "BIT 6,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 70 ", "BIT 6,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 72 ", "BIT 6,(IX+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 76 ", "BIT 6,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 73 ", "BIT 6,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 70 ", "BIT 6,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 75 ", "BIT 6,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 74 ", "BIT 6,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 72 ", "BIT 6,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 77 ", "BIT 6,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 71 ", "BIT 6,(IY+%d)     ", 20));
			Instructions.Add(Instruction("CB77       ", "BIT 6,A           ", 8));
			Instructions.Add(Instruction("CB70       ", "BIT 6,B           ", 8));
			Instructions.Add(Instruction("CB71       ", "BIT 6,C           ", 8));
			Instructions.Add(Instruction("CB72       ", "BIT 6,D           ", 8));
			Instructions.Add(Instruction("CB73       ", "BIT 6,E           ", 8));
			Instructions.Add(Instruction("CB74       ", "BIT 6,H           ", 8));
			Instructions.Add(Instruction("CB75       ", "BIT 6,L           ", 8));

			Instructions.Add(Instruction("CB7E       ", "BIT 7,(HL)        ", 12));
			Instructions.Add(Instruction("DDCB %d 7E ", "BIT 7,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 7B ", "BIT 7,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 79 ", "BIT 7,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 7F ", "BIT 7,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 7C ", "BIT 7,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 7A ", "BIT 7,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 7D ", "BIT 7,(IX+%d)     ", 20));
			Instructions.Add(Instruction("DDCB %d 78 ", "BIT 7,(IX+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 7E ", "BIT 7,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 78 ", "BIT 7,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 7A ", "BIT 7,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 7F ", "BIT 7,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 7C ", "BIT 7,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 7B ", "BIT 7,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 79 ", "BIT 7,(IY+%d)     ", 20));
			Instructions.Add(Instruction("FDCB %d 7D ", "BIT 7,(IY+%d)     ", 20));
			Instructions.Add(Instruction("CB7F       ", "BIT 7,A           ", 8));
			Instructions.Add(Instruction("CB78       ", "BIT 7,B           ", 8));
			Instructions.Add(Instruction("CB79       ", "BIT 7,C           ", 8));
			Instructions.Add(Instruction("CB7A       ", "BIT 7,D           ", 8));
			Instructions.Add(Instruction("CB7B       ", "BIT 7,E           ", 8));
			Instructions.Add(Instruction("CB7C       ", "BIT 7,H           ", 8));
			Instructions.Add(Instruction("CB7D       ", "BIT 7,L           ", 8));

			Instructions.Add(Instruction("CD %nn     ", "CALL (%nn)        ", 17));
			Instructions.Add(Instruction("DC %nn     ", "CALL C,(%nn)      ", 17, 10));
			Instructions.Add(Instruction("FC %nn     ", "CALL M,(%nn)      ", 17, 10));
			Instructions.Add(Instruction("D4 %nn     ", "CALL NC,(%nn)     ", 17, 10));
			Instructions.Add(Instruction("C4 %nn     ", "CALL NZ,(%nn)     ", 17, 10));
			Instructions.Add(Instruction("F4 %nn     ", "CALL P,(%nn)      ", 17, 10));
			Instructions.Add(Instruction("EC %nn     ", "CALL PE,(%nn)     ", 17, 10));
			Instructions.Add(Instruction("E4 %nn     ", "CALL PO,(%nn)     ", 17, 10));
			Instructions.Add(Instruction("CC %nn     ", "CALL Z,(%nn)      ", 17, 10));

			Instructions.Add(Instruction("3F         ", "CCF               ", 4));

			Instructions.Add(Instruction("BF         ", "CP A              ", 4));
			Instructions.Add(Instruction("B8         ", "CP B              ", 4));
			Instructions.Add(Instruction("B9         ", "CP C              ", 4));
			Instructions.Add(Instruction("BA         ", "CP D              ", 4));
			Instructions.Add(Instruction("BB         ", "CP E              ", 4));
			Instructions.Add(Instruction("BC         ", "CP H              ", 4));
			Instructions.Add(Instruction("DDBC       ", "CP IXh            ", 4));
			Instructions.Add(Instruction("DDBD       ", "CP IXl            ", 4));
			Instructions.Add(Instruction("FDBC       ", "CP IYh            ", 4));
			Instructions.Add(Instruction("FDBD       ", "CP IYl            ", 4));
			Instructions.Add(Instruction("BD         ", "CP L              ", 4));
			Instructions.Add(Instruction("FE %n      ", "CP %n             ", 7));
			Instructions.Add(Instruction("BE         ", "CP (HL)           ", 7));
			Instructions.Add(Instruction("DDBE %d    ", "CP (IX+%d)        ", 19));
			Instructions.Add(Instruction("FDBE %d    ", "CP (IY+%d)        ", 19));

			Instructions.Add(Instruction("EDA9       ", "CPD               ", 16));
			Instructions.Add(Instruction("EDB9       ", "CPDR              ", 21, 16));
			Instructions.Add(Instruction("EDA1       ", "CPI               ", 16));
			Instructions.Add(Instruction("EDB1       ", "CPIR              ", 21, 16));
			Instructions.Add(Instruction("2F         ", "CPL               ", 4));
			Instructions.Add(Instruction("27         ", "DAA               ", 4));

			Instructions.Add(Instruction("3D         ", "DEC A             ", 4));
			Instructions.Add(Instruction("05         ", "DEC B             ", 4));
			Instructions.Add(Instruction("0D         ", "DEC C             ", 4));
			Instructions.Add(Instruction("15         ", "DEC D             ", 4));
			Instructions.Add(Instruction("1D         ", "DEC E             ", 4));
			Instructions.Add(Instruction("25         ", "DEC H             ", 4));
			Instructions.Add(Instruction("2D         ", "DEC L             ", 4));
			Instructions.Add(Instruction("DD25       ", "DEC IXh           ", 4));
			Instructions.Add(Instruction("DD2D       ", "DEC IXl           ", 4));
			Instructions.Add(Instruction("FD25       ", "DEC IYh           ", 4));
			Instructions.Add(Instruction("FD2D       ", "DEC IYl           ", 4));
			Instructions.Add(Instruction("35         ", "DEC (HL)          ", 11));
			Instructions.Add(Instruction("DD35 %d    ", "DEC (IX+%d)       ", 23));
			Instructions.Add(Instruction("FD35 %d    ", "DEC (IY+%d)       ", 23));

			Instructions.Add(Instruction("DD2B       ", "DEC IX            ", 10));
			Instructions.Add(Instruction("FD2B       ", "DEC IY            ", 10));
			Instructions.Add(Instruction("0B         ", "DEC BC            ", 6));
			Instructions.Add(Instruction("1B         ", "DEC DE            ", 6));
			Instructions.Add(Instruction("2B         ", "DEC HL            ", 6));
			Instructions.Add(Instruction("3B         ", "DEC SP            ", 6));

			Instructions.Add(Instruction("F3         ", "DI                ", 4));

			Instructions.Add(Instruction("10 %e      ", "DJNZ (PC+%e)      ", 13, 8));

			Instructions.Add(Instruction("FB         ", "EI                ", 4));

			Instructions.Add(Instruction("E3         ", "EX (SP),HL        ", 19));
			Instructions.Add(Instruction("DDE3       ", "EX (SP),IX        ", 23));
			Instructions.Add(Instruction("FDE3       ", "EX (SP),IY        ", 23));
			Instructions.Add(Instruction("08         ", "EX AF,AF'         ", 4));
			Instructions.Add(Instruction("EB         ", "EX DE,HL          ", 4));
			Instructions.Add(Instruction("D9         ", "EXX               ", 4));
			Instructions.Add(Instruction("76         ", "HALT              ", 4));

			Instructions.Add(Instruction("ED46       ", "IM 0              ", 8));
			Instructions.Add(Instruction("ED6E       ", "IM 0              ", 8));
			Instructions.Add(Instruction("ED4E       ", "IM 0              ", 8));
			Instructions.Add(Instruction("ED66       ", "IM 0              ", 8));
			Instructions.Add(Instruction("ED56       ", "IM 1              ", 8));
			Instructions.Add(Instruction("ED76       ", "IM 1              ", 8));
			Instructions.Add(Instruction("ED5E       ", "IM 2              ", 8));
			Instructions.Add(Instruction("ED7E       ", "IM 2              ", 8));

			Instructions.Add(Instruction("DB %n      ", "IN A,(%n)         ", 11));
			Instructions.Add(Instruction("ED78       ", "IN A,(C)          ", 12));
			Instructions.Add(Instruction("ED40       ", "IN B,(C)          ", 12));
			Instructions.Add(Instruction("ED48       ", "IN C,(C)          ", 12));
			Instructions.Add(Instruction("ED50       ", "IN D,(C)          ", 12));
			Instructions.Add(Instruction("ED58       ", "IN E,(C)          ", 12));
			Instructions.Add(Instruction("ED70       ", "IN F,(C)          ", 12));
			Instructions.Add(Instruction("ED60       ", "IN H,(C)          ", 12));
			Instructions.Add(Instruction("ED68       ", "IN L,(C)          ", 12));

			Instructions.Add(Instruction("3C         ", "INC A             ", 4));
			Instructions.Add(Instruction("04         ", "INC B             ", 4));
			Instructions.Add(Instruction("0C         ", "INC C             ", 4));
			Instructions.Add(Instruction("14         ", "INC D             ", 4));
			Instructions.Add(Instruction("1C         ", "INC E             ", 4));
			Instructions.Add(Instruction("24         ", "INC H             ", 4));
			Instructions.Add(Instruction("2C         ", "INC L             ", 4));
			Instructions.Add(Instruction("DD24       ", "INC IXh           ", 4));
			Instructions.Add(Instruction("DD2C       ", "INC IXl           ", 4));
			Instructions.Add(Instruction("FD24       ", "INC IYh           ", 4));
			Instructions.Add(Instruction("FD2C       ", "INC IYl           ", 4));
			Instructions.Add(Instruction("34         ", "INC (HL)          ", 11));
			Instructions.Add(Instruction("DD34 %d    ", "INC (IX+%d)       ", 23));
			Instructions.Add(Instruction("FD34 %d    ", "INC (IY+%d)       ", 23));

			Instructions.Add(Instruction("DD23       ", "INC IX            ", 10));
			Instructions.Add(Instruction("FD23       ", "INC IY            ", 10));
			Instructions.Add(Instruction("03         ", "INC BC            ", 6));
			Instructions.Add(Instruction("13         ", "INC DE            ", 6));
			Instructions.Add(Instruction("23         ", "INC HL            ", 6));
			Instructions.Add(Instruction("33         ", "INC SP            ", 6));

			Instructions.Add(Instruction("EDAA       ", "IND               ", 16));
			Instructions.Add(Instruction("EDBA       ", "INDR              ", 21, 16));
			Instructions.Add(Instruction("EDA2       ", "INI               ", 16));
			Instructions.Add(Instruction("EDB2       ", "INIR              ", 21, 16));

			Instructions.Add(Instruction("C3 %nn     ", "JP (%nn)          ", 10));
			Instructions.Add(Instruction("DA %nn     ", "JP C,(%nn)        ", 10));
			Instructions.Add(Instruction("FA %nn     ", "JP M,(%nn)        ", 10));
			Instructions.Add(Instruction("D2 %nn     ", "JP NC,(%nn)       ", 10));
			Instructions.Add(Instruction("C2 %nn     ", "JP NZ,(%nn)       ", 10));
			Instructions.Add(Instruction("F2 %nn     ", "JP P,(%nn)        ", 10));
			Instructions.Add(Instruction("EA %nn     ", "JP PE,(%nn)       ", 10));
			Instructions.Add(Instruction("E2 %nn     ", "JP PO,(%nn)       ", 10));
			Instructions.Add(Instruction("CA %nn     ", "JP Z,(%nn)        ", 10));

			Instructions.Add(Instruction("E9         ", "JP (HL)           ", 4));
			Instructions.Add(Instruction("DDE9       ", "JP (IX)           ", 8));
			Instructions.Add(Instruction("FDE9       ", "JP (IY)           ", 8));

			Instructions.Add(Instruction("38 %e      ", "JR C,(PC+%e)      ", 12, 7));
			Instructions.Add(Instruction("18 %e      ", "JR (PC+%e)        ", 12));
			Instructions.Add(Instruction("30 %e      ", "JR NC,(PC+%e)     ", 12, 7));
			Instructions.Add(Instruction("20 %e      ", "JR NZ,(PC+%e)     ", 12, 7));
			Instructions.Add(Instruction("28 %e      ", "JR Z,(PC+%e)      ", 12, 7));

			Instructions.Add(Instruction("0A         ", "LD A,(BC)         ", 7));
			Instructions.Add(Instruction("1A         ", "LD A,(DE)         ", 7));
			Instructions.Add(Instruction("ED57       ", "LD A,I            ", 9));
			Instructions.Add(Instruction("3A %nn     ", "LD A,(%nn)        ", 13));
			Instructions.Add(Instruction("7F         ", "LD A,A            ", 9));
			Instructions.Add(Instruction("78         ", "LD A,B            ", 9));
			Instructions.Add(Instruction("79         ", "LD A,C            ", 9));
			Instructions.Add(Instruction("7A         ", "LD A,D            ", 9));
			Instructions.Add(Instruction("7B         ", "LD A,E            ", 9));
			Instructions.Add(Instruction("7C         ", "LD A,H            ", 9));
			Instructions.Add(Instruction("DD7C       ", "LD A,IXh          ", 9));
			Instructions.Add(Instruction("DD7D       ", "LD A,IXl          ", 9));
			Instructions.Add(Instruction("FD7C       ", "LD A,IYh          ", 9));
			Instructions.Add(Instruction("FD7D       ", "LD A,IYl          ", 9));

			Instructions.Add(Instruction("02         ", "LD (BC),A         ", 7));
			Instructions.Add(Instruction("12         ", "LD (DE),A         ", 7));
			Instructions.Add(Instruction("36 %n      ", "LD (HL),%n        ", 10));

			Instructions.Add(Instruction("77         ", "LD (HL),A         ", 7));
			Instructions.Add(Instruction("70         ", "LD (HL),B         ", 7));
			Instructions.Add(Instruction("71         ", "LD (HL),C         ", 7));
			Instructions.Add(Instruction("72         ", "LD (HL),D         ", 7));
			Instructions.Add(Instruction("73         ", "LD (HL),E         ", 7));
			Instructions.Add(Instruction("74         ", "LD (HL),H         ", 7));
			Instructions.Add(Instruction("75         ", "LD (HL),L         ", 7));

			Instructions.Add(Instruction("DD77 %d    ", "LD (IX+%d),A      ", 16));
			Instructions.Add(Instruction("DD70 %d    ", "LD (IX+%d),B      ", 16));
			Instructions.Add(Instruction("DD71 %d    ", "LD (IX+%d),C      ", 16));
			Instructions.Add(Instruction("DD72 %d    ", "LD (IX+%d),D      ", 16));
			Instructions.Add(Instruction("DD73 %d    ", "LD (IX+%d),E      ", 16));
			Instructions.Add(Instruction("DD74 %d    ", "LD (IX+%d),H      ", 16));
			Instructions.Add(Instruction("DD75 %d    ", "LD (IX+%d),L      ", 16));
			Instructions.Add(Instruction("FD77 %d    ", "LD (IY+%d),A      ", 16));
			Instructions.Add(Instruction("FD70 %d    ", "LD (IY+%d),B      ", 16));
			Instructions.Add(Instruction("FD71 %d    ", "LD (IY+%d),C      ", 16));
			Instructions.Add(Instruction("FD72 %d    ", "LD (IY+%d),D      ", 16));
			Instructions.Add(Instruction("FD73 %d    ", "LD (IY+%d),E      ", 16));
			Instructions.Add(Instruction("FD74 %d    ", "LD (IY+%d),H      ", 16));
			Instructions.Add(Instruction("FD75 %d    ", "LD (IY+%d),L      ", 16));
			Instructions.Add(Instruction("DD36 %d %n ", "LD (IX+%d),%n     ", 19));
			Instructions.Add(Instruction("FD36 %d %n ", "LD (IY+%d),%n     ", 19));

			Instructions.Add(Instruction("32 %nn     ", "LD (%nn),A        ", 13));
			Instructions.Add(Instruction("ED43 %nn   ", "LD (%nn),BC       ", 20));
			Instructions.Add(Instruction("ED53 %nn   ", "LD (%nn),DE       ", 20));
			Instructions.Add(Instruction("ED63 %nn   ", "LD (%nn),HL       ", 16));
			Instructions.Add(Instruction("22 %nn     ", "LD (%nn),HL       ", 16));
			Instructions.Add(Instruction("ED73 %nn   ", "LD (%nn),SP       ", 20));

			Instructions.Add(Instruction("DD22 %nn   ", "LD (%nn),IX       ", 20));
			Instructions.Add(Instruction("FD22 %nn   ", "LD (%nn),IY       ", 20));


			Instructions.Add(Instruction("7E         ", "LD A,(HL)         "));
			Instructions.Add(Instruction("DD7E %d    ", "LD A,(IX+%d)      "));
			Instructions.Add(Instruction("FD7E %d    ", "LD A,(IY+%d)      "));
			Instructions.Add(Instruction("7D         ", "LD A,L            "));
			Instructions.Add(Instruction("3E %n      ", "LD A,%n           "));
			Instructions.Add(Instruction("ED5F       ", "LD A,R            "));
			Instructions.Add(Instruction("DDCB %d 87 ", "LD A,RES 0,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d 87 ", "LD A,RES 0,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d 8F ", "LD A,RES 1,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d 8F ", "LD A,RES 1,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d 97 ", "LD A,RES 2,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d 97 ", "LD A,RES 2,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d 9F ", "LD A,RES 3,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d 9F ", "LD A,RES 3,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d A7 ", "LD A,RES 4,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d A7 ", "LD A,RES 4,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d AF ", "LD A,RES 5,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d AF ", "LD A,RES 5,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d B7 ", "LD A,RES 6,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d B7 ", "LD A,RES 6,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d BF ", "LD A,RES 7,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d BF ", "LD A,RES 7,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d 17 ", "LD A,RL (IX+%d)   "));
			Instructions.Add(Instruction("FDCB %d 17 ", "LD A,RL (IY+%d)   "));
			Instructions.Add(Instruction("DDCB %d 07 ", "LD A,RLC (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 07 ", "LD A,RLC (IY+%d)  "));
			Instructions.Add(Instruction("DDCB %d 1F ", "LD A,RR (IX+%d)   "));
			Instructions.Add(Instruction("FDCB %d 1F ", "LD A,RR (IY+%d)   "));
			Instructions.Add(Instruction("DDCB %d 0F ", "LD A,RRC (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 0F ", "LD A,RRC (IY+%d)  "));
			Instructions.Add(Instruction("DDCB %d C7 ", "LD A,SET 0,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d C7 ", "LD A,SET 0,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d CF ", "LD A,SET 1,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d CF ", "LD A,SET 1,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d D7 ", "LD A,SET 2,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d D7 ", "LD A,SET 2,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d DF ", "LD A,SET 3,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d DF ", "LD A,SET 3,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d E7 ", "LD A,SET 4,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d E7 ", "LD A,SET 4,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d EF ", "LD A,SET 5,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d EF ", "LD A,SET 5,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d F7 ", "LD A,SET 6,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d F7 ", "LD A,SET 6,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d FF ", "LD A,SET 7,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d FF ", "LD A,SET 7,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d 27 ", "LD A,SLA (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 27 ", "LD A,SLA (IY+%d)  "));
			Instructions.Add(Instruction("DDCB %d 37 ", "LD A,SLL (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 37 ", "LD A,SLL (IY+%d)  "));
			Instructions.Add(Instruction("DDCB %d 2F ", "LD A,SRA (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 2F ", "LD A,SRA (IY+%d)  "));
			Instructions.Add(Instruction("DDCB %d 3F ", "LD A,SRL (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 3F ", "LD A,SRL (IY+%d)  "));
			Instructions.Add(Instruction("46         ", "LD B,(HL)         "));
			Instructions.Add(Instruction("DD46 %d    ", "LD B,(IX+%d)      "));
			Instructions.Add(Instruction("FD46 %d    ", "LD B,(IY+%d)      "));
			Instructions.Add(Instruction("47         ", "LD B,A            "));
			Instructions.Add(Instruction("40         ", "LD B,B            "));
			Instructions.Add(Instruction("41         ", "LD B,C            "));
			Instructions.Add(Instruction("42         ", "LD B,D            "));
			Instructions.Add(Instruction("43         ", "LD B,E            "));
			Instructions.Add(Instruction("44         ", "LD B,H            "));
			Instructions.Add(Instruction("DD44       ", "LD B,IXh          "));
			Instructions.Add(Instruction("DD45       ", "LD B,IXl          "));
			Instructions.Add(Instruction("FD44       ", "LD B,IYh          "));
			Instructions.Add(Instruction("FD45       ", "LD B,IYl          "));
			Instructions.Add(Instruction("45         ", "LD B,L            "));
			Instructions.Add(Instruction("06 %n      ", "LD B,%n           "));
			Instructions.Add(Instruction("DDCB %d 80 ", "LD B,RES 0,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d 80 ", "LD B,RES 0,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d 88 ", "LD B,RES 1,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d 88 ", "LD B,RES 1,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d 90 ", "LD B,RES 2,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d 90 ", "LD B,RES 2,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d 98 ", "LD B,RES 3,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d 98 ", "LD B,RES 3,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d A0 ", "LD B,RES 4,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d A0 ", "LD B,RES 4,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d A8 ", "LD B,RES 5,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d A8 ", "LD B,RES 5,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d B0 ", "LD B,RES 6,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d B0 ", "LD B,RES 6,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d B8 ", "LD B,RES 7,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d B8 ", "LD B,RES 7,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d 10 ", "LD B,RL (IX+%d)   "));
			Instructions.Add(Instruction("FDCB %d 10 ", "LD B,RL (IY+%d)   "));
			Instructions.Add(Instruction("DDCB %d 00 ", "LD B,RLC (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 00 ", "LD B,RLC (IY+%d)  "));
			Instructions.Add(Instruction("DDCB %d 18 ", "LD B,RR (IX+%d)   "));
			Instructions.Add(Instruction("FDCB %d 18 ", "LD B,RR (IY+%d)   "));
			Instructions.Add(Instruction("DDCB %d 08 ", "LD B,RRC (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 08 ", "LD B,RRC (IY+%d)  "));
			Instructions.Add(Instruction("DDCB %d C0 ", "LD B,SET 0,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d C0 ", "LD B,SET 0,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d C8 ", "LD B,SET 1,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d C8 ", "LD B,SET 1,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d D0 ", "LD B,SET 2,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d D0 ", "LD B,SET 2,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d D8 ", "LD B,SET 3,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d D8 ", "LD B,SET 3,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d E0 ", "LD B,SET 4,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d E0 ", "LD B,SET 4,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d E8 ", "LD B,SET 5,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d E8 ", "LD B,SET 5,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d F0 ", "LD B,SET 6,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d F0 ", "LD B,SET 6,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d F8 ", "LD B,SET 7,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d F8 ", "LD B,SET 7,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d 20 ", "LD B,SLA (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 20 ", "LD B,SLA (IY+%d)  "));
			Instructions.Add(Instruction("DDCB %d 30 ", "LD B,SLL (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 30 ", "LD B,SLL (IY+%d)  "));
			Instructions.Add(Instruction("DDCB %d 28 ", "LD B,SRA (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 28 ", "LD B,SRA (IY+%d)  "));
			Instructions.Add(Instruction("DDCB %d 38 ", "LD B,SRL (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 38 ", "LD B,SRL (IY+%d)  "));
			Instructions.Add(Instruction("ED4B %nn   ", "LD BC,(%nn)       "));
			Instructions.Add(Instruction("01 %nn     ", "LD BC,%nn         "));
			Instructions.Add(Instruction("4E         ", "LD C,(HL)         "));
			Instructions.Add(Instruction("DD4E %d    ", "LD C,(IX+%d)      "));
			Instructions.Add(Instruction("FD4E %d    ", "LD C,(IY+%d)      "));
			Instructions.Add(Instruction("4F         ", "LD C,A            "));
			Instructions.Add(Instruction("48         ", "LD C,B            "));
			Instructions.Add(Instruction("49         ", "LD C,C            "));
			Instructions.Add(Instruction("4A         ", "LD C,D            "));
			Instructions.Add(Instruction("4B         ", "LD C,E            "));
			Instructions.Add(Instruction("4C         ", "LD C,H            "));
			Instructions.Add(Instruction("DD4C       ", "LD C,IXh          "));
			Instructions.Add(Instruction("DD4D       ", "LD C,IXl          "));
			Instructions.Add(Instruction("FD4C       ", "LD C,IYh          "));
			Instructions.Add(Instruction("FD4D       ", "LD C,IYl          "));
			Instructions.Add(Instruction("4D         ", "LD C,L            "));
			Instructions.Add(Instruction("0E %n      ", "LD C,%n           "));
			Instructions.Add(Instruction("DDCB %d 81 ", "LD C,RES 0,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d 81 ", "LD C,RES 0,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d 89 ", "LD C,RES 1,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d 89 ", "LD C,RES 1,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d 91 ", "LD C,RES 2,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d 91 ", "LD C,RES 2,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d 99 ", "LD C,RES 3,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d 99 ", "LD C,RES 3,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d A1 ", "LD C,RES 4,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d A1 ", "LD C,RES 4,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d A9 ", "LD C,RES 5,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d A9 ", "LD C,RES 5,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d B1 ", "LD C,RES 6,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d B1 ", "LD C,RES 6,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d B9 ", "LD C,RES 7,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d B9 ", "LD C,RES 7,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d 11 ", "LD C,RL (IX+%d)   "));
			Instructions.Add(Instruction("FDCB %d 11 ", "LD C,RL (IY+%d)   "));
			Instructions.Add(Instruction("DDCB %d 01 ", "LD C,RLC (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 01 ", "LD C,RLC (IY+%d)  "));
			Instructions.Add(Instruction("DDCB %d 19 ", "LD C,RR (IX+%d)   "));
			Instructions.Add(Instruction("FDCB %d 19 ", "LD C,RR (IY+%d)   "));
			Instructions.Add(Instruction("DDCB %d 09 ", "LD C,RRC (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 09 ", "LD C,RRC (IY+%d)  "));
			Instructions.Add(Instruction("DDCB %d C1 ", "LD C,SET 0,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d C1 ", "LD C,SET 0,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d C9 ", "LD C,SET 1,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d C9 ", "LD C,SET 1,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d D1 ", "LD C,SET 2,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d D1 ", "LD C,SET 2,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d D9 ", "LD C,SET 3,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d D9 ", "LD C,SET 3,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d E1 ", "LD C,SET 4,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d E1 ", "LD C,SET 4,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d E9 ", "LD C,SET 5,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d E9 ", "LD C,SET 5,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d F1 ", "LD C,SET 6,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d F1 ", "LD C,SET 6,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d F9 ", "LD C,SET 7,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d F9 ", "LD C,SET 7,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d 21 ", "LD C,SLA (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 21 ", "LD C,SLA (IY+%d)  "));
			Instructions.Add(Instruction("DDCB %d 31 ", "LD C,SLL (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 31 ", "LD C,SLL (IY+%d)  "));
			Instructions.Add(Instruction("DDCB %d 29 ", "LD C,SRA (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 29 ", "LD C,SRA (IY+%d)  "));
			Instructions.Add(Instruction("DDCB %d 39 ", "LD C,SRL (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 39 ", "LD C,SRL (IY+%d)  "));
			Instructions.Add(Instruction("56         ", "LD D,(HL)         "));
			Instructions.Add(Instruction("DD56 %d    ", "LD D,(IX+%d)      "));
			Instructions.Add(Instruction("FD56 %d    ", "LD D,(IY+%d)      "));
			Instructions.Add(Instruction("57         ", "LD D,A            "));
			Instructions.Add(Instruction("50         ", "LD D,B            "));
			Instructions.Add(Instruction("51         ", "LD D,C            "));
			Instructions.Add(Instruction("52         ", "LD D,D            "));
			Instructions.Add(Instruction("53         ", "LD D,E            "));
			Instructions.Add(Instruction("54         ", "LD D,H            "));
			Instructions.Add(Instruction("DD54       ", "LD D,IXh          "));
			Instructions.Add(Instruction("DD55       ", "LD D,IXl          "));
			Instructions.Add(Instruction("FD54       ", "LD D,IYh          "));
			Instructions.Add(Instruction("FD55       ", "LD D,IYl          "));
			Instructions.Add(Instruction("55         ", "LD D,L            "));
			Instructions.Add(Instruction("16 %n      ", "LD D,%n           "));
			Instructions.Add(Instruction("DDCB %d 82 ", "LD D,RES 0,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d 82 ", "LD D,RES 0,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d 8A ", "LD D,RES 1,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d 8A ", "LD D,RES 1,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d 92 ", "LD D,RES 2,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d 92 ", "LD D,RES 2,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d 9A ", "LD D,RES 3,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d 9A ", "LD D,RES 3,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d A2 ", "LD D,RES 4,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d A2 ", "LD D,RES 4,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d AA ", "LD D,RES 5,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d AA ", "LD D,RES 5,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d B2 ", "LD D,RES 6,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d B2 ", "LD D,RES 6,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d BA ", "LD D,RES 7,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d BA ", "LD D,RES 7,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d 12 ", "LD D,RL (IX+%d)   "));
			Instructions.Add(Instruction("FDCB %d 12 ", "LD D,RL (IY+%d)   "));
			Instructions.Add(Instruction("DDCB %d 02 ", "LD D,RLC (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 02 ", "LD D,RLC (IY+%d)  "));
			Instructions.Add(Instruction("DDCB %d 1A ", "LD D,RR (IX+%d)   "));
			Instructions.Add(Instruction("FDCB %d 1A ", "LD D,RR (IY+%d)   "));
			Instructions.Add(Instruction("DDCB %d 0A ", "LD D,RRC (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 0A ", "LD D,RRC (IY+%d)  "));
			Instructions.Add(Instruction("DDCB %d C2 ", "LD D,SET 0,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d C2 ", "LD D,SET 0,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d CA ", "LD D,SET 1,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d CA ", "LD D,SET 1,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d D2 ", "LD D,SET 2,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d D2 ", "LD D,SET 2,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d DA ", "LD D,SET 3,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d DA ", "LD D,SET 3,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d E2 ", "LD D,SET 4,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d E2 ", "LD D,SET 4,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d EA ", "LD D,SET 5,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d EA ", "LD D,SET 5,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d F2 ", "LD D,SET 6,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d F2 ", "LD D,SET 6,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d FA ", "LD D,SET 7,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d FA ", "LD D,SET 7,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d 22 ", "LD D,SLA (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 22 ", "LD D,SLA (IY+%d)  "));
			Instructions.Add(Instruction("DDCB %d 32 ", "LD D,SLL (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 32 ", "LD D,SLL (IY+%d)  "));
			Instructions.Add(Instruction("DDCB %d 2A ", "LD D,SRA (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 2A ", "LD D,SRA (IY+%d)  "));
			Instructions.Add(Instruction("DDCB %d 3A ", "LD D,SRL (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 3A ", "LD D,SRL (IY+%d)  "));
			Instructions.Add(Instruction("ED5B %nn   ", "LD DE,(%nn)       "));
			Instructions.Add(Instruction("11 %nn     ", "LD DE,%nn         "));
			Instructions.Add(Instruction("5E         ", "LD E,(HL)         "));
			Instructions.Add(Instruction("DD5E %d    ", "LD E,(IX+%d)      "));
			Instructions.Add(Instruction("FD5E %d    ", "LD E,(IY+%d)      "));
			Instructions.Add(Instruction("5F         ", "LD E,A            "));
			Instructions.Add(Instruction("58         ", "LD E,B            "));
			Instructions.Add(Instruction("59         ", "LD E,C            "));
			Instructions.Add(Instruction("5A         ", "LD E,D            "));
			Instructions.Add(Instruction("5B         ", "LD E,E            "));
			Instructions.Add(Instruction("5C         ", "LD E,H            "));
			Instructions.Add(Instruction("DD5C       ", "LD E,IXh          "));
			Instructions.Add(Instruction("DD5D       ", "LD E,IXl          "));
			Instructions.Add(Instruction("FD5C       ", "LD E,IYh          "));
			Instructions.Add(Instruction("FD5D       ", "LD E,IYl          "));
			Instructions.Add(Instruction("5D         ", "LD E,L            "));
			Instructions.Add(Instruction("1E %n      ", "LD E,%n           "));
			Instructions.Add(Instruction("DDCB %d 83 ", "LD E,RES 0,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d 83 ", "LD E,RES 0,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d 8B ", "LD E,RES 1,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d 8B ", "LD E,RES 1,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d 93 ", "LD E,RES 2,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d 93 ", "LD E,RES 2,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d 9B ", "LD E,RES 3,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d 9B ", "LD E,RES 3,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d A3 ", "LD E,RES 4,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d A3 ", "LD E,RES 4,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d AB ", "LD E,RES 5,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d AB ", "LD E,RES 5,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d B3 ", "LD E,RES 6,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d B3 ", "LD E,RES 6,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d BB ", "LD E,RES 7,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d BB ", "LD E,RES 7,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d 13 ", "LD E,RL (IX+%d)   "));
			Instructions.Add(Instruction("FDCB %d 13 ", "LD E,RL (IY+%d)   "));
			Instructions.Add(Instruction("DDCB %d 03 ", "LD E,RLC (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 03 ", "LD E,RLC (IY+%d)  "));
			Instructions.Add(Instruction("DDCB %d 1B ", "LD E,RR (IX+%d)   "));
			Instructions.Add(Instruction("FDCB %d 1B ", "LD E,RR (IY+%d)   "));
			Instructions.Add(Instruction("DDCB %d 0B ", "LD E,RRC (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 0B ", "LD E,RRC (IY+%d)  "));
			Instructions.Add(Instruction("DDCB %d C3 ", "LD E,SET 0,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d C3 ", "LD E,SET 0,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d CB ", "LD E,SET 1,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d CB ", "LD E,SET 1,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d D3 ", "LD E,SET 2,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d D3 ", "LD E,SET 2,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d DB ", "LD E,SET 3,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d DB ", "LD E,SET 3,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d E3 ", "LD E,SET 4,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d E3 ", "LD E,SET 4,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d EB ", "LD E,SET 5,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d EB ", "LD E,SET 5,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d F3 ", "LD E,SET 6,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d F3 ", "LD E,SET 6,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d FB ", "LD E,SET 7,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d FB ", "LD E,SET 7,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d 23 ", "LD E,SLA (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 23 ", "LD E,SLA (IY+%d)  "));
			Instructions.Add(Instruction("DDCB %d 33 ", "LD E,SLL (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 33 ", "LD E,SLL (IY+%d)  "));
			Instructions.Add(Instruction("DDCB %d 2B ", "LD E,SRA (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 2B ", "LD E,SRA (IY+%d)  "));
			Instructions.Add(Instruction("DDCB %d 3B ", "LD E,SRL (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 3B ", "LD E,SRL (IY+%d)  "));
			Instructions.Add(Instruction("66         ", "LD H,(HL)         "));
			Instructions.Add(Instruction("DD66 %d    ", "LD H,(IX+%d)      "));
			Instructions.Add(Instruction("FD66 %d    ", "LD H,(IY+%d)      "));
			Instructions.Add(Instruction("67         ", "LD H,A            "));
			Instructions.Add(Instruction("60         ", "LD H,B            "));
			Instructions.Add(Instruction("61         ", "LD H,C            "));
			Instructions.Add(Instruction("62         ", "LD H,D            "));
			Instructions.Add(Instruction("63         ", "LD H,E            "));
			Instructions.Add(Instruction("64         ", "LD H,H            "));
			Instructions.Add(Instruction("65         ", "LD H,L            "));
			Instructions.Add(Instruction("26 %n      ", "LD H,%n           "));
			Instructions.Add(Instruction("DDCB %d 84 ", "LD H,RES 0,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d 84 ", "LD H,RES 0,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d 8C ", "LD H,RES 1,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d 8C ", "LD H,RES 1,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d 94 ", "LD H,RES 2,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d 94 ", "LD H,RES 2,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d 9C ", "LD H,RES 3,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d 9C ", "LD H,RES 3,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d A4 ", "LD H,RES 4,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d A4 ", "LD H,RES 4,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d AC ", "LD H,RES 5,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d AC ", "LD H,RES 5,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d B4 ", "LD H,RES 6,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d B4 ", "LD H,RES 6,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d BC ", "LD H,RES 7,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d BC ", "LD H,RES 7,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d 14 ", "LD H,RL (IX+%d)   "));
			Instructions.Add(Instruction("FDCB %d 14 ", "LD H,RL (IY+%d)   "));
			Instructions.Add(Instruction("DDCB %d 04 ", "LD H,RLC (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 04 ", "LD H,RLC (IY+%d)  "));
			Instructions.Add(Instruction("DDCB %d 1C ", "LD H,RR (IX+%d)   "));
			Instructions.Add(Instruction("FDCB %d 1C ", "LD H,RR (IY+%d)   "));
			Instructions.Add(Instruction("DDCB %d 0C ", "LD H,RRC (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 0C ", "LD H,RRC (IY+%d)  "));
			Instructions.Add(Instruction("DDCB %d C4 ", "LD H,SET 0,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d C4 ", "LD H,SET 0,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d CC ", "LD H,SET 1,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d CC ", "LD H,SET 1,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d D4 ", "LD H,SET 2,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d D4 ", "LD H,SET 2,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d DC ", "LD H,SET 3,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d DC ", "LD H,SET 3,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d E4 ", "LD H,SET 4,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d E4 ", "LD H,SET 4,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d EC ", "LD H,SET 5,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d EC ", "LD H,SET 5,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d F4 ", "LD H,SET 6,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d F4 ", "LD H,SET 6,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d FC ", "LD H,SET 7,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d FC ", "LD H,SET 7,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d 24 ", "LD H,SLA (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 24 ", "LD H,SLA (IY+%d)  "));
			Instructions.Add(Instruction("DDCB %d 34 ", "LD H,SLL (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 34 ", "LD H,SLL (IY+%d)  "));
			Instructions.Add(Instruction("DDCB %d 2C ", "LD H,SRA (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 2C ", "LD H,SRA (IY+%d)  "));
			Instructions.Add(Instruction("DDCB %d 3C ", "LD H,SRL (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 3C ", "LD H,SRL (IY+%d)  "));
			Instructions.Add(Instruction("ED6B %nn   ", "LD HL,(%nn)       "));
			Instructions.Add(Instruction("2A %nn     ", "LD HL,(%nn)       "));
			Instructions.Add(Instruction("21 %nn     ", "LD HL,%nn         "));
			Instructions.Add(Instruction("ED47       ", "LD I,A            "));
			Instructions.Add(Instruction("DD2A %nn   ", "LD IX,(%nn)       "));
			Instructions.Add(Instruction("DD21 %nn   ", "LD IX,%nn         "));
			Instructions.Add(Instruction("DD67       ", "LD IXh,A          "));
			Instructions.Add(Instruction("DD60       ", "LD IXh,B          "));
			Instructions.Add(Instruction("DD61       ", "LD IXh,C          "));
			Instructions.Add(Instruction("DD62       ", "LD IXh,D          "));
			Instructions.Add(Instruction("DD63       ", "LD IXh,E          "));
			Instructions.Add(Instruction("DD64       ", "LD IXh,IXh        "));
			Instructions.Add(Instruction("DD65       ", "LD IXh,IXl        "));
			Instructions.Add(Instruction("DD26 %n    ", "LD IXh,%n         "));
			Instructions.Add(Instruction("DD6F       ", "LD IXl,A          "));
			Instructions.Add(Instruction("DD68       ", "LD IXl,B          "));
			Instructions.Add(Instruction("DD69       ", "LD IXl,C          "));
			Instructions.Add(Instruction("DD6A       ", "LD IXl,D          "));
			Instructions.Add(Instruction("DD6B       ", "LD IXl,E          "));
			Instructions.Add(Instruction("DD6C       ", "LD IXl,IXh        "));
			Instructions.Add(Instruction("DD6D       ", "LD IXl,IXl        "));
			Instructions.Add(Instruction("DD2E %n    ", "LD IXl,%n         "));
			Instructions.Add(Instruction("FD2A %nn   ", "LD IY,(%nn)       "));
			Instructions.Add(Instruction("FD21 %nn   ", "LD IY,%nn         "));
			Instructions.Add(Instruction("FD67       ", "LD IYh,A          "));
			Instructions.Add(Instruction("FD60       ", "LD IYh,B          "));
			Instructions.Add(Instruction("FD61       ", "LD IYh,C          "));
			Instructions.Add(Instruction("FD62       ", "LD IYh,D          "));
			Instructions.Add(Instruction("FD63       ", "LD IYh,E          "));
			Instructions.Add(Instruction("FD64       ", "LD IYh,IYh        "));
			Instructions.Add(Instruction("FD65       ", "LD IYh,IYl        "));
			Instructions.Add(Instruction("FD26 %n    ", "LD IYh,%n         "));
			Instructions.Add(Instruction("FD6F       ", "LD IYl,A          "));
			Instructions.Add(Instruction("FD68       ", "LD IYl,B          "));
			Instructions.Add(Instruction("FD69       ", "LD IYl,C          "));
			Instructions.Add(Instruction("FD6A       ", "LD IYl,D          "));
			Instructions.Add(Instruction("FD6B       ", "LD IYl,E          "));
			Instructions.Add(Instruction("FD6C       ", "LD IYl,IYh        "));
			Instructions.Add(Instruction("FD6D       ", "LD IYl,IYl        "));
			Instructions.Add(Instruction("FD2E %n    ", "LD IYl,%n         "));
			Instructions.Add(Instruction("6E         ", "LD L,(HL)         "));
			Instructions.Add(Instruction("DD6E %d    ", "LD L,(IX+%d)      "));
			Instructions.Add(Instruction("FD6E %d    ", "LD L,(IY+%d)      "));
			Instructions.Add(Instruction("6F         ", "LD L,A            "));
			Instructions.Add(Instruction("68         ", "LD L,B            "));
			Instructions.Add(Instruction("69         ", "LD L,C            "));
			Instructions.Add(Instruction("6A         ", "LD L,D            "));
			Instructions.Add(Instruction("6B         ", "LD L,E            "));
			Instructions.Add(Instruction("6C         ", "LD L,H            "));
			Instructions.Add(Instruction("6D         ", "LD L,L            "));
			Instructions.Add(Instruction("2E %n      ", "LD L,%n           "));
			Instructions.Add(Instruction("DDCB %d 85 ", "LD L,RES 0,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d 85 ", "LD L,RES 0,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d 8D ", "LD L,RES 1,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d 8D ", "LD L,RES 1,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d 95 ", "LD L,RES 2,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d 95 ", "LD L,RES 2,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d 9D ", "LD L,RES 3,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d 9D ", "LD L,RES 3,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d A5 ", "LD L,RES 4,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d A5 ", "LD L,RES 4,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d AD ", "LD L,RES 5,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d AD ", "LD L,RES 5,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d B5 ", "LD L,RES 6,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d B5 ", "LD L,RES 6,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d BD ", "LD L,RES 7,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d BD ", "LD L,RES 7,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d 15 ", "LD L,RL (IX+%d)   "));
			Instructions.Add(Instruction("FDCB %d 15 ", "LD L,RL (IY+%d)   "));
			Instructions.Add(Instruction("DDCB %d 05 ", "LD L,RLC (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 05 ", "LD L,RLC (IY+%d)  "));
			Instructions.Add(Instruction("DDCB %d 1D ", "LD L,RR (IX+%d)   "));
			Instructions.Add(Instruction("FDCB %d 1D ", "LD L,RR (IY+%d)   "));
			Instructions.Add(Instruction("DDCB %d 0D ", "LD L,RRC (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 0D ", "LD L,RRC (IY+%d)  "));
			Instructions.Add(Instruction("DDCB %d C5 ", "LD L,SET 0,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d C5 ", "LD L,SET 0,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d CD ", "LD L,SET 1,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d CD ", "LD L,SET 1,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d D5 ", "LD L,SET 2,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d D5 ", "LD L,SET 2,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d DD ", "LD L,SET 3,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d DD ", "LD L,SET 3,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d E5 ", "LD L,SET 4,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d E5 ", "LD L,SET 4,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d ED ", "LD L,SET 5,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d ED ", "LD L,SET 5,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d F5 ", "LD L,SET 6,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d F5 ", "LD L,SET 6,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d FD ", "LD L,SET 7,(IX+%d)"));
			Instructions.Add(Instruction("FDCB %d FD ", "LD L,SET 7,(IY+%d)"));
			Instructions.Add(Instruction("DDCB %d 25 ", "LD L,SLA (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 25 ", "LD L,SLA (IY+%d)  "));
			Instructions.Add(Instruction("DDCB %d 35 ", "LD L,SLL (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 35 ", "LD L,SLL (IY+%d)  "));
			Instructions.Add(Instruction("DDCB %d 2D ", "LD L,SRA (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 2D ", "LD L,SRA (IY+%d)  "));
			Instructions.Add(Instruction("DDCB %d 3D ", "LD L,SRL (IX+%d)  "));
			Instructions.Add(Instruction("FDCB %d 3D ", "LD L,SRL (IY+%d)  "));
			Instructions.Add(Instruction("ED4F       ", "LD R,A            "));
			Instructions.Add(Instruction("ED7B %nn   ", "LD SP,(%nn)       "));
			Instructions.Add(Instruction("F9         ", "LD SP,HL          "));
			Instructions.Add(Instruction("DDF9       ", "LD SP,IX          "));
			Instructions.Add(Instruction("FDF9       ", "LD SP,IY          "));
			Instructions.Add(Instruction("31 %nn     ", "LD SP,%nn         "));

			Instructions.Add(Instruction("EDA8       ", "LDD               ", 16));
			Instructions.Add(Instruction("EDB8       ", "LDDR              ", 21, 16));

			Instructions.Add(Instruction("EDA0       ", "LDI               ", 16));
			Instructions.Add(Instruction("EDB0       ", "LDIR              ", 21, 17));

			Instructions.Add(Instruction("ED44       ", "NEG               ", 8));
			Instructions.Add(Instruction("ED64       ", "NEG               ", 8));
			Instructions.Add(Instruction("ED6C       ", "NEG               ", 8));
			Instructions.Add(Instruction("ED74       ", "NEG               ", 8));
			Instructions.Add(Instruction("ED5C       ", "NEG               ", 8));
			Instructions.Add(Instruction("ED7C       ", "NEG               ", 8));
			Instructions.Add(Instruction("ED54       ", "NEG               ", 8));
			Instructions.Add(Instruction("ED4C       ", "NEG               ", 8));

			Instructions.Add(Instruction("00         ", "NOP               ", 4));

			Instructions.Add(Instruction("B7         ", "OR A              ", 4));
			Instructions.Add(Instruction("B0         ", "OR B              ", 4));
			Instructions.Add(Instruction("B1         ", "OR C              ", 4));
			Instructions.Add(Instruction("B2         ", "OR D              ", 4));
			Instructions.Add(Instruction("B3         ", "OR E              ", 4));
			Instructions.Add(Instruction("B4         ", "OR H              ", 4));
			Instructions.Add(Instruction("DDB4       ", "OR IXh            ", 4));
			Instructions.Add(Instruction("DDB5       ", "OR IXl            ", 4));
			Instructions.Add(Instruction("FDB4       ", "OR IYh            ", 4));
			Instructions.Add(Instruction("FDB5       ", "OR IYl            ", 4));
			Instructions.Add(Instruction("B5         ", "OR L              ", 4));
			Instructions.Add(Instruction("F6 %n      ", "OR %n             ", 7));
			Instructions.Add(Instruction("B6         ", "OR (HL)           ", 7));
			Instructions.Add(Instruction("DDB6 %d    ", "OR (IX+%d)        ", 19));
			Instructions.Add(Instruction("FDB6 %d    ", "OR (IY+%d)        ", 19));

			Instructions.Add(Instruction("EDBB       ", "OTDR              ", 21, 16));
			Instructions.Add(Instruction("EDB3       ", "OTIR              ", 21, 16));

			Instructions.Add(Instruction("ED71       ", "OUT (C),0         ", 12));
			Instructions.Add(Instruction("ED79       ", "OUT (C),A         ", 12));
			Instructions.Add(Instruction("ED41       ", "OUT (C),B         ", 12));
			Instructions.Add(Instruction("ED49       ", "OUT (C),C         ", 12));
			Instructions.Add(Instruction("ED51       ", "OUT (C),D         ", 12));
			Instructions.Add(Instruction("ED59       ", "OUT (C),E         ", 12));
			Instructions.Add(Instruction("ED61       ", "OUT (C),H         ", 12));
			Instructions.Add(Instruction("ED69       ", "OUT (C),L         ", 12));

			Instructions.Add(Instruction("D3 %n      ", "OUT (%n),A        ", 11));

			Instructions.Add(Instruction("EDAB       ", "OUTD              ", 16));
			Instructions.Add(Instruction("EDA3       ", "OUTI              ", 16));

			Instructions.Add(Instruction("DDE1       ", "POP IX            ", 14));
			Instructions.Add(Instruction("FDE1       ", "POP IY            ", 14));
			Instructions.Add(Instruction("C1         ", "POP BC            ", 10));
			Instructions.Add(Instruction("D1         ", "POP DE            ", 10));
			Instructions.Add(Instruction("E1         ", "POP HL            ", 10));
			Instructions.Add(Instruction("F1         ", "POP AF            ", 10));

			Instructions.Add(Instruction("DDE5       ", "PUSH IX           ", 15));
			Instructions.Add(Instruction("FDE5       ", "PUSH IY           ", 15));
			Instructions.Add(Instruction("C5         ", "PUSH BC           ", 11));
			Instructions.Add(Instruction("D5         ", "PUSH DE           ", 11));
			Instructions.Add(Instruction("E5         ", "PUSH HL           ", 11));
			Instructions.Add(Instruction("F5         ", "PUSH AF           ", 11));

			Instructions.Add(Instruction("CB87       ", "RES 0,A           ", 8));
			Instructions.Add(Instruction("CB80       ", "RES 0,B           ", 8));
			Instructions.Add(Instruction("CB81       ", "RES 0,C           ", 8));
			Instructions.Add(Instruction("CB82       ", "RES 0,D           ", 8));
			Instructions.Add(Instruction("CB83       ", "RES 0,E           ", 8));
			Instructions.Add(Instruction("CB84       ", "RES 0,H           ", 8));
			Instructions.Add(Instruction("CB85       ", "RES 0,L           ", 8));
			Instructions.Add(Instruction("CB86       ", "RES 0,(HL)        ", 15));
			Instructions.Add(Instruction("DDCB %d 86 ", "RES 0,(IX+%d)     ", 23));
			Instructions.Add(Instruction("FDCB %d 86 ", "RES 0,(IY+%d)     ", 23));

			Instructions.Add(Instruction("CB8F       ", "RES 1,A           ", 8));
			Instructions.Add(Instruction("CB88       ", "RES 1,B           ", 8));
			Instructions.Add(Instruction("CB89       ", "RES 1,C           ", 8));
			Instructions.Add(Instruction("CB8A       ", "RES 1,D           ", 8));
			Instructions.Add(Instruction("CB8B       ", "RES 1,E           ", 8));
			Instructions.Add(Instruction("CB8C       ", "RES 1,H           ", 8));
			Instructions.Add(Instruction("CB8D       ", "RES 1,L           ", 8));
			Instructions.Add(Instruction("CB8E       ", "RES 1,(HL)        ", 15));
			Instructions.Add(Instruction("DDCB %d 8E ", "RES 1,(IX+%d)     ", 23));
			Instructions.Add(Instruction("FDCB %d 8E ", "RES 1,(IY+%d)     ", 23));

			Instructions.Add(Instruction("CB97       ", "RES 2,A           ", 8));
			Instructions.Add(Instruction("CB90       ", "RES 2,B           ", 8));
			Instructions.Add(Instruction("CB91       ", "RES 2,C           ", 8));
			Instructions.Add(Instruction("CB92       ", "RES 2,D           ", 8));
			Instructions.Add(Instruction("CB93       ", "RES 2,E           ", 8));
			Instructions.Add(Instruction("CB94       ", "RES 2,H           ", 8));
			Instructions.Add(Instruction("CB95       ", "RES 2,L           ", 8));
			Instructions.Add(Instruction("CB96       ", "RES 2,(HL)        ", 15));
			Instructions.Add(Instruction("DDCB %d 96 ", "RES 2,(IX+%d)     ", 23));
			Instructions.Add(Instruction("FDCB %d 96 ", "RES 2,(IY+%d)     ", 23));

			Instructions.Add(Instruction("CB9F       ", "RES 3,A           ", 8));
			Instructions.Add(Instruction("CB98       ", "RES 3,B           ", 8));
			Instructions.Add(Instruction("CB99       ", "RES 3,C           ", 8));
			Instructions.Add(Instruction("CB9A       ", "RES 3,D           ", 8));
			Instructions.Add(Instruction("CB9B       ", "RES 3,E           ", 8));
			Instructions.Add(Instruction("CB9C       ", "RES 3,H           ", 8));
			Instructions.Add(Instruction("CB9D       ", "RES 3,L           ", 8));
			Instructions.Add(Instruction("CB9E       ", "RES 3,(HL)        ", 15));
			Instructions.Add(Instruction("DDCB %d 9E ", "RES 3,(IX+%d)     ", 23));
			Instructions.Add(Instruction("FDCB %d 9E ", "RES 3,(IY+%d)     ", 23));

			Instructions.Add(Instruction("CBA7       ", "RES 4,A           ", 8));
			Instructions.Add(Instruction("CBA0       ", "RES 4,B           ", 8));
			Instructions.Add(Instruction("CBA1       ", "RES 4,C           ", 8));
			Instructions.Add(Instruction("CBA2       ", "RES 4,D           ", 8));
			Instructions.Add(Instruction("CBA3       ", "RES 4,E           ", 8));
			Instructions.Add(Instruction("CBA4       ", "RES 4,H           ", 8));
			Instructions.Add(Instruction("CBA5       ", "RES 4,L           ", 8));
			Instructions.Add(Instruction("CBA6       ", "RES 4,(HL)        ", 15));
			Instructions.Add(Instruction("DDCB %d A6 ", "RES 4,(IX+%d)     ", 23));
			Instructions.Add(Instruction("FDCB %d A6 ", "RES 4,(IY+%d)     ", 23));

			Instructions.Add(Instruction("CBAF       ", "RES 5,A           ", 8));
			Instructions.Add(Instruction("CBA8       ", "RES 5,B           ", 8));
			Instructions.Add(Instruction("CBA9       ", "RES 5,C           ", 8));
			Instructions.Add(Instruction("CBAA       ", "RES 5,D           ", 8));
			Instructions.Add(Instruction("CBAB       ", "RES 5,E           ", 8));
			Instructions.Add(Instruction("CBAC       ", "RES 5,H           ", 8));
			Instructions.Add(Instruction("CBAD       ", "RES 5,L           ", 8));
			Instructions.Add(Instruction("CBAE       ", "RES 5,(HL)        ", 15));
			Instructions.Add(Instruction("DDCB %d AE ", "RES 5,(IX+%d)     ", 23));
			Instructions.Add(Instruction("FDCB %d AE ", "RES 5,(IY+%d)     ", 23));

			Instructions.Add(Instruction("CBB7       ", "RES 6,A           ", 8));
			Instructions.Add(Instruction("CBB0       ", "RES 6,B           ", 8));
			Instructions.Add(Instruction("CBB1       ", "RES 6,C           ", 8));
			Instructions.Add(Instruction("CBB2       ", "RES 6,D           ", 8));
			Instructions.Add(Instruction("CBB3       ", "RES 6,E           ", 8));
			Instructions.Add(Instruction("CBB4       ", "RES 6,H           ", 8));
			Instructions.Add(Instruction("CBB5       ", "RES 6,L           ", 8));
			Instructions.Add(Instruction("CBB6       ", "RES 6,(HL)        ", 15));
			Instructions.Add(Instruction("DDCB %d B6 ", "RES 6,(IX+%d)     ", 23));
			Instructions.Add(Instruction("FDCB %d B6 ", "RES 6,(IY+%d)     ", 23));

			Instructions.Add(Instruction("CBBF       ", "RES 7,A           ", 8));
			Instructions.Add(Instruction("CBB8       ", "RES 7,B           ", 8));
			Instructions.Add(Instruction("CBB9       ", "RES 7,C           ", 8));
			Instructions.Add(Instruction("CBBA       ", "RES 7,D           ", 8));
			Instructions.Add(Instruction("CBBB       ", "RES 7,E           ", 8));
			Instructions.Add(Instruction("CBBC       ", "RES 7,H           ", 8));
			Instructions.Add(Instruction("CBBD       ", "RES 7,L           ", 8));
			Instructions.Add(Instruction("CBBE       ", "RES 7,(HL)        ", 15));
			Instructions.Add(Instruction("DDCB %d BE ", "RES 7,(IX+%d)     ", 23));
			Instructions.Add(Instruction("FDCB %d BE ", "RES 7,(IY+%d)     ", 23));

			Instructions.Add(Instruction("C9         ", "RET               ", 10));
			Instructions.Add(Instruction("D8         ", "RET C             ", 11, 5));
			Instructions.Add(Instruction("F8         ", "RET M             ", 11, 5));
			Instructions.Add(Instruction("D0         ", "RET NC            ", 11, 5));
			Instructions.Add(Instruction("C0         ", "RET NZ            ", 11, 5));
			Instructions.Add(Instruction("F0         ", "RET P             ", 11, 5));
			Instructions.Add(Instruction("E8         ", "RET PE            ", 11, 5));
			Instructions.Add(Instruction("E0         ", "RET PO            ", 11, 5));
			Instructions.Add(Instruction("C8         ", "RET Z             ", 11, 5));

			Instructions.Add(Instruction("ED4D       ", "RETI              ", 14));
			Instructions.Add(Instruction("ED45       ", "RETN              ", 14));
			Instructions.Add(Instruction("ED55       ", "RETN              ", 14));
			Instructions.Add(Instruction("ED65       ", "RETN              ", 14));
			Instructions.Add(Instruction("ED5D       ", "RETN              ", 14));
			Instructions.Add(Instruction("ED75       ", "RETN              ", 14));
			Instructions.Add(Instruction("ED6D       ", "RETN              ", 14));
			Instructions.Add(Instruction("ED7D       ", "RETN              ", 14));

			Instructions.Add(Instruction("CB17       ", "RL A              ", 8));
			Instructions.Add(Instruction("CB10       ", "RL B              ", 8));
			Instructions.Add(Instruction("CB11       ", "RL C              ", 8));
			Instructions.Add(Instruction("CB12       ", "RL D              ", 8));
			Instructions.Add(Instruction("CB13       ", "RL E              ", 8));
			Instructions.Add(Instruction("CB14       ", "RL H              ", 8));
			Instructions.Add(Instruction("CB15       ", "RL L              ", 8));
			Instructions.Add(Instruction("CB16       ", "RL (HL)           ", 15));
			Instructions.Add(Instruction("DDCB %d 16 ", "RL (IX+%d)        ", 23));
			Instructions.Add(Instruction("FDCB %d 16 ", "RL (IY+%d)        ", 23));
			
			Instructions.Add(Instruction("17         ", "RLA               ", 4));

			Instructions.Add(Instruction("CB07       ", "RLC A             ", 8));
			Instructions.Add(Instruction("CB00       ", "RLC B             ", 8));
			Instructions.Add(Instruction("CB01       ", "RLC C             ", 8));
			Instructions.Add(Instruction("CB02       ", "RLC D             ", 8));
			Instructions.Add(Instruction("CB03       ", "RLC E             ", 8));
			Instructions.Add(Instruction("CB04       ", "RLC H             ", 8));
			Instructions.Add(Instruction("CB05       ", "RLC L             ", 8));
			Instructions.Add(Instruction("CB06       ", "RLC (HL)          ", 15));
			Instructions.Add(Instruction("DDCB %d 06 ", "RLC (IX+%d)       ", 23));
			Instructions.Add(Instruction("FDCB %d 06 ", "RLC (IY+%d)       ", 23));
			
			Instructions.Add(Instruction("07         ", "RLCA              ", 4));
			Instructions.Add(Instruction("ED6F       ", "RLD               ", 18));

			Instructions.Add(Instruction("CB1F       ", "RR A              ", 8));
			Instructions.Add(Instruction("CB18       ", "RR B              ", 8));
			Instructions.Add(Instruction("CB19       ", "RR C              ", 8));
			Instructions.Add(Instruction("CB1A       ", "RR D              ", 8));
			Instructions.Add(Instruction("CB1B       ", "RR E              ", 8));
			Instructions.Add(Instruction("CB1C       ", "RR H              ", 8));
			Instructions.Add(Instruction("CB1D       ", "RR L              ", 8));
			Instructions.Add(Instruction("CB1E       ", "RR (HL)           ", 15));
			Instructions.Add(Instruction("DDCB %d 1E ", "RR (IX+%d)        ", 23));
			Instructions.Add(Instruction("FDCB %d 1E ", "RR (IY+%d)        ", 23));

			Instructions.Add(Instruction("1F         ", "RRA               ", 4));

			Instructions.Add(Instruction("CB0F       ", "RRC A             ", 8));
			Instructions.Add(Instruction("CB08       ", "RRC B             ", 8));
			Instructions.Add(Instruction("CB09       ", "RRC C             ", 8));
			Instructions.Add(Instruction("CB0A       ", "RRC D             ", 8));
			Instructions.Add(Instruction("CB0B       ", "RRC E             ", 8));
			Instructions.Add(Instruction("CB0C       ", "RRC H             ", 8));
			Instructions.Add(Instruction("CB0D       ", "RRC L             ", 8));
			Instructions.Add(Instruction("CB0E       ", "RRC (HL)          ", 15));
			Instructions.Add(Instruction("DDCB %d 0E ", "RRC (IX+%d)       ", 23));
			Instructions.Add(Instruction("FDCB %d 0E ", "RRC (IY+%d)       ", 23));

			Instructions.Add(Instruction("0F         ", "RRCA              ", 4));
			Instructions.Add(Instruction("ED67       ", "RRD               ", 18));

			Instructions.Add(Instruction("C7         ", "RST 0H            ", 11));
			Instructions.Add(Instruction("CF         ", "RST 8H            ", 11));
			Instructions.Add(Instruction("D7         ", "RST 10H           ", 11));
			Instructions.Add(Instruction("DF         ", "RST 18H           ", 11));
			Instructions.Add(Instruction("E7         ", "RST 20H           ", 11));
			Instructions.Add(Instruction("EF         ", "RST 28H           ", 11));
			Instructions.Add(Instruction("F7         ", "RST 30H           ", 11));
			Instructions.Add(Instruction("FF         ", "RST 38H           ", 11));

			Instructions.Add(Instruction("9F         ", "SBC A,A           ", 4));
			Instructions.Add(Instruction("98         ", "SBC A,B           ", 4));
			Instructions.Add(Instruction("99         ", "SBC A,C           ", 4));
			Instructions.Add(Instruction("9A         ", "SBC A,D           ", 4));
			Instructions.Add(Instruction("9B         ", "SBC A,E           ", 4));
			Instructions.Add(Instruction("9C         ", "SBC A,H           ", 4));
			Instructions.Add(Instruction("DD9C       ", "SBC A,IXh         ", 4));
			Instructions.Add(Instruction("DD9D       ", "SBC A,IXl         ", 4));
			Instructions.Add(Instruction("FD9C       ", "SBC A,IYh         ", 4));
			Instructions.Add(Instruction("FD9D       ", "SBC A,IYl         ", 4));
			Instructions.Add(Instruction("9D         ", "SBC A,L           ", 4));
			Instructions.Add(Instruction("DE %n      ", "SBC A,%n          ", 7));
			Instructions.Add(Instruction("9E         ", "SBC A,(HL)        ", 7));
			Instructions.Add(Instruction("DD9E %d    ", "SBC A,(IX+%d)     ", 19));
			Instructions.Add(Instruction("FD9E %d    ", "SBC A,(IY+%d)     ", 19));
			Instructions.Add(Instruction("ED42       ", "SBC HL,BC         ", 15));
			Instructions.Add(Instruction("ED52       ", "SBC HL,DE         ", 15));
			Instructions.Add(Instruction("ED62       ", "SBC HL,HL         ", 15));
			Instructions.Add(Instruction("ED72       ", "SBC HL,SP         ", 15));

			Instructions.Add(Instruction("37         ", "SCF               ", 4));

			Instructions.Add(Instruction("CBC6       ", "SET 0,(HL)        ", 15));
			Instructions.Add(Instruction("DDCB %d C6 ", "SET 0,(IX+%d)     ", 23));
			Instructions.Add(Instruction("FDCB %d C6 ", "SET 0,(IY+%d)     ", 23));
			Instructions.Add(Instruction("CBC7       ", "SET 0,A           ", 8));
			Instructions.Add(Instruction("CBC0       ", "SET 0,B           ", 8));
			Instructions.Add(Instruction("CBC1       ", "SET 0,C           ", 8));
			Instructions.Add(Instruction("CBC2       ", "SET 0,D           ", 8));
			Instructions.Add(Instruction("CBC3       ", "SET 0,E           ", 8));
			Instructions.Add(Instruction("CBC4       ", "SET 0,H           ", 8));
			Instructions.Add(Instruction("CBC5       ", "SET 0,L           ", 8));

			Instructions.Add(Instruction("CBCE       ", "SET 1,(HL)        ", 15));
			Instructions.Add(Instruction("DDCB %d CE ", "SET 1,(IX+%d)     ", 23));
			Instructions.Add(Instruction("FDCB %d CE ", "SET 1,(IY+%d)     ", 23));
			Instructions.Add(Instruction("CBCF       ", "SET 1,A           ", 8));
			Instructions.Add(Instruction("CBC8       ", "SET 1,B           ", 8));
			Instructions.Add(Instruction("CBC9       ", "SET 1,C           ", 8));
			Instructions.Add(Instruction("CBCA       ", "SET 1,D           ", 8));
			Instructions.Add(Instruction("CBCB       ", "SET 1,E           ", 8));
			Instructions.Add(Instruction("CBCC       ", "SET 1,H           ", 8));
			Instructions.Add(Instruction("CBCD       ", "SET 1,L           ", 8));

			Instructions.Add(Instruction("CBD6       ", "SET 2,(HL)        ", 15));
			Instructions.Add(Instruction("DDCB %d D6 ", "SET 2,(IX+%d)     ", 23));
			Instructions.Add(Instruction("FDCB %d D6 ", "SET 2,(IY+%d)     ", 23));
			Instructions.Add(Instruction("CBD7       ", "SET 2,A           ", 8));
			Instructions.Add(Instruction("CBD0       ", "SET 2,B           ", 8));
			Instructions.Add(Instruction("CBD1       ", "SET 2,C           ", 8));
			Instructions.Add(Instruction("CBD2       ", "SET 2,D           ", 8));
			Instructions.Add(Instruction("CBD3       ", "SET 2,E           ", 8));
			Instructions.Add(Instruction("CBD4       ", "SET 2,H           ", 8));
			Instructions.Add(Instruction("CBD5       ", "SET 2,L           ", 8));

			Instructions.Add(Instruction("CBDE       ", "SET 3,(HL)        ", 15));
			Instructions.Add(Instruction("DDCB %d DE ", "SET 3,(IX+%d)     ", 23));
			Instructions.Add(Instruction("FDCB %d DE ", "SET 3,(IY+%d)     ", 23));
			Instructions.Add(Instruction("CBDF       ", "SET 3,A           ", 8));
			Instructions.Add(Instruction("CBD8       ", "SET 3,B           ", 8));
			Instructions.Add(Instruction("CBD9       ", "SET 3,C           ", 8));
			Instructions.Add(Instruction("CBDA       ", "SET 3,D           ", 8));
			Instructions.Add(Instruction("CBDB       ", "SET 3,E           ", 8));
			Instructions.Add(Instruction("CBDC       ", "SET 3,H           ", 8));
			Instructions.Add(Instruction("CBDD       ", "SET 3,L           ", 8));

			Instructions.Add(Instruction("CBE6       ", "SET 4,(HL)        ", 15));
			Instructions.Add(Instruction("DDCB %d E6 ", "SET 4,(IX+%d)     ", 23));
			Instructions.Add(Instruction("FDCB %d E6 ", "SET 4,(IY+%d)     ", 23));
			Instructions.Add(Instruction("CBE7       ", "SET 4,A           ", 8));
			Instructions.Add(Instruction("CBE0       ", "SET 4,B           ", 8));
			Instructions.Add(Instruction("CBE1       ", "SET 4,C           ", 8));
			Instructions.Add(Instruction("CBE2       ", "SET 4,D           ", 8));
			Instructions.Add(Instruction("CBE3       ", "SET 4,E           ", 8));
			Instructions.Add(Instruction("CBE4       ", "SET 4,H           ", 8));
			Instructions.Add(Instruction("CBE5       ", "SET 4,L           ", 8));

			Instructions.Add(Instruction("CBEE       ", "SET 5,(HL)        ", 15));
			Instructions.Add(Instruction("DDCB %d EE ", "SET 5,(IX+%d)     ", 23));
			Instructions.Add(Instruction("FDCB %d EE ", "SET 5,(IY+%d)     ", 23));
			Instructions.Add(Instruction("CBEF       ", "SET 5,A           ", 8));
			Instructions.Add(Instruction("CBE8       ", "SET 5,B           ", 8));
			Instructions.Add(Instruction("CBE9       ", "SET 5,C           ", 8));
			Instructions.Add(Instruction("CBEA       ", "SET 5,D           ", 8));
			Instructions.Add(Instruction("CBEB       ", "SET 5,E           ", 8));
			Instructions.Add(Instruction("CBEC       ", "SET 5,H           ", 8));
			Instructions.Add(Instruction("CBED       ", "SET 5,L           ", 8));

			Instructions.Add(Instruction("CBF6       ", "SET 6,(HL)        ", 15));
			Instructions.Add(Instruction("DDCB %d F6 ", "SET 6,(IX+%d)     ", 23));
			Instructions.Add(Instruction("FDCB %d F6 ", "SET 6,(IY+%d)     ", 23));
			Instructions.Add(Instruction("CBF7       ", "SET 6,A           ", 8));
			Instructions.Add(Instruction("CBF0       ", "SET 6,B           ", 8));
			Instructions.Add(Instruction("CBF1       ", "SET 6,C           ", 8));
			Instructions.Add(Instruction("CBF2       ", "SET 6,D           ", 8));
			Instructions.Add(Instruction("CBF3       ", "SET 6,E           ", 8));
			Instructions.Add(Instruction("CBF4       ", "SET 6,H           ", 8));
			Instructions.Add(Instruction("CBF5       ", "SET 6,L           ", 8));

			Instructions.Add(Instruction("CBFE       ", "SET 7,(HL)        ", 15));
			Instructions.Add(Instruction("DDCB %d FE ", "SET 7,(IX+%d)     ", 23));
			Instructions.Add(Instruction("FDCB %d FE ", "SET 7,(IY+%d)     ", 23));
			Instructions.Add(Instruction("CBFF       ", "SET 7,A           ", 8));
			Instructions.Add(Instruction("CBF8       ", "SET 7,B           ", 8));
			Instructions.Add(Instruction("CBF9       ", "SET 7,C           ", 8));
			Instructions.Add(Instruction("CBFA       ", "SET 7,D           ", 8));
			Instructions.Add(Instruction("CBFB       ", "SET 7,E           ", 8));
			Instructions.Add(Instruction("CBFC       ", "SET 7,H           ", 8));
			Instructions.Add(Instruction("CBFD       ", "SET 7,L           ", 8));

			Instructions.Add(Instruction("CB27       ", "SLA A             ", 8));
			Instructions.Add(Instruction("CB20       ", "SLA B             ", 8));
			Instructions.Add(Instruction("CB21       ", "SLA C             ", 8));
			Instructions.Add(Instruction("CB22       ", "SLA D             ", 8));
			Instructions.Add(Instruction("CB23       ", "SLA E             ", 8));
			Instructions.Add(Instruction("CB24       ", "SLA H             ", 8));
			Instructions.Add(Instruction("CB25       ", "SLA L             ", 8));
			Instructions.Add(Instruction("CB26       ", "SLA (HL)          ", 15));
			Instructions.Add(Instruction("DDCB %d 26 ", "SLA (IX+%d)       ", 23));
			Instructions.Add(Instruction("FDCB %d 26 ", "SLA (IY+%d)       ", 23));

			Instructions.Add(Instruction("CB37       ", "SLL A             ", 8));
			Instructions.Add(Instruction("CB30       ", "SLL B             ", 8));
			Instructions.Add(Instruction("CB31       ", "SLL C             ", 8));
			Instructions.Add(Instruction("CB32       ", "SLL D             ", 8));
			Instructions.Add(Instruction("CB33       ", "SLL E             ", 8));
			Instructions.Add(Instruction("CB34       ", "SLL H             ", 8));
			Instructions.Add(Instruction("CB35       ", "SLL L             ", 8));
			Instructions.Add(Instruction("CB36       ", "SLL (HL)          ", 15));
			Instructions.Add(Instruction("DDCB %d 36 ", "SLL (IX+%d)       ", 23));
			Instructions.Add(Instruction("FDCB %d 36 ", "SLL (IY+%d)       ", 23));

			Instructions.Add(Instruction("CB2F       ", "SRA A             ", 8));
			Instructions.Add(Instruction("CB28       ", "SRA B             ", 8));
			Instructions.Add(Instruction("CB29       ", "SRA C             ", 8));
			Instructions.Add(Instruction("CB2A       ", "SRA D             ", 8));
			Instructions.Add(Instruction("CB2B       ", "SRA E             ", 8));
			Instructions.Add(Instruction("CB2C       ", "SRA H             ", 8));
			Instructions.Add(Instruction("CB2D       ", "SRA L             ", 8));
			Instructions.Add(Instruction("CB2E       ", "SRA (HL)          ", 15));
			Instructions.Add(Instruction("DDCB %d 2E ", "SRA (IX+%d)       ", 23));
			Instructions.Add(Instruction("FDCB %d 2E ", "SRA (IY+%d)       ", 23));

			Instructions.Add(Instruction("CB3F       ", "SRL A             ", 8));
			Instructions.Add(Instruction("CB38       ", "SRL B             ", 8));
			Instructions.Add(Instruction("CB39       ", "SRL C             ", 8));
			Instructions.Add(Instruction("CB3A       ", "SRL D             ", 8));
			Instructions.Add(Instruction("CB3B       ", "SRL E             ", 8));
			Instructions.Add(Instruction("CB3C       ", "SRL H             ", 8));
			Instructions.Add(Instruction("CB3D       ", "SRL L             ", 8));
			Instructions.Add(Instruction("CB3E       ", "SRL (HL)          ", 15));
			Instructions.Add(Instruction("DDCB %d 3E ", "SRL (IX+%d)       ", 23));
			Instructions.Add(Instruction("FDCB %d 3E ", "SRL (IY+%d)       ", 23));

			Instructions.Add(Instruction("97         ", "SUB A,A           ", 4));
			Instructions.Add(Instruction("90         ", "SUB A,B           ", 4));
			Instructions.Add(Instruction("91         ", "SUB A,C           ", 4));
			Instructions.Add(Instruction("92         ", "SUB A,D           ", 4));
			Instructions.Add(Instruction("93         ", "SUB A,E           ", 4));
			Instructions.Add(Instruction("94         ", "SUB A,H           ", 4));
			Instructions.Add(Instruction("DD94       ", "SUB A,IXh         ", 4));
			Instructions.Add(Instruction("DD95       ", "SUB A,IXl         ", 4));
			Instructions.Add(Instruction("FD94       ", "SUB A,IYh         ", 4));
			Instructions.Add(Instruction("FD95       ", "SUB A,IYl         ", 4));
			Instructions.Add(Instruction("95         ", "SUB A,L           ", 4));
			Instructions.Add(Instruction("D6 %n      ", "SUB A,%n          ", 7));
			Instructions.Add(Instruction("96         ", "SUB A,(HL)        ", 7));
			Instructions.Add(Instruction("DD96 %d    ", "SUB A,(IX+%d)     ", 19));
			Instructions.Add(Instruction("FD96 %d    ", "SUB A,(IY+%d)     ", 19));

			Instructions.Add(Instruction("AF         ", "XOR A             ", 4));
			Instructions.Add(Instruction("A8         ", "XOR B             ", 4));
			Instructions.Add(Instruction("A9         ", "XOR C             ", 4));
			Instructions.Add(Instruction("AA         ", "XOR D             ", 4));
			Instructions.Add(Instruction("AB         ", "XOR E             ", 4));
			Instructions.Add(Instruction("AC         ", "XOR H             ", 4));
			Instructions.Add(Instruction("DDAC       ", "XOR IXh           ", 4));
			Instructions.Add(Instruction("DDAD       ", "XOR IXl           ", 4));
			Instructions.Add(Instruction("FDAC       ", "XOR IYh           ", 4));
			Instructions.Add(Instruction("FDAD       ", "XOR IYl           ", 4));
			Instructions.Add(Instruction("AD         ", "XOR L             ", 4));
			Instructions.Add(Instruction("EE %n      ", "XOR %n            ", 7));
			Instructions.Add(Instruction("AE         ", "XOR (HL)          ", 7));
			Instructions.Add(Instruction("DDAE %d    ", "XOR (IX+%d)       ", 19));
			Instructions.Add(Instruction("FDAE %d    ", "XOR (IY+%d)       ", 19));

			return Instructions.ToArray();
		}

		private static Lazy<InstructionInfo[]> _Instructions = new Lazy<InstructionInfo[]>(() => CreateInstructionList(Version.Z80));
	}
}
